### ISSUE TITLE
habdroid+my.openhab socket leak

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab.android#102]
Hi,

I'm sorry to disturb with an annoyance I'm suffering, but after several uses of the current development snapshot built with android studio, my.openhab binding does seem to have a problem with #62 and does not close sockets completely:

```
# lsof -a -i -u openhab
java    21451 openhab 2230u  IPv4 113102357      0t0  TCP localhost:42931->localhost:http-alt (CLOSE_WAIT)
java    21451 openhab 2236u  IPv4 113100435      0t0  TCP localhost:42932->localhost:http-alt (CLOSE_WAIT)
java    21451 openhab 2242u  IPv4 113100437      0t0  TCP localhost:42934->localhost:http-alt (CLOSE_WAIT)
java    21451 openhab 2244u  IPv4 113102364      0t0  TCP localhost:42935->localhost:http-alt (CLOSE_WAIT)
java    21451 openhab 2248u  IPv4 113102367      0t0  TCP localhost:42938->localhost:http-alt (CLOSE_WAIT)
root@openhab:/usr/share/openhab/addons# lsof -a -i -uopenhab | grep CLOSE_WAIT | wc -l
1654
```

This works until several thousands are still open - then, openhab needs to be restarted.

My environment may be causing the problem:
  - current bleeding edge habdroid
  - openhab 1.6.1
  - current my.openhab binding
  - only seems to affect connections from 3G, not WiFi

@digitaldan did you test against current openhab snapshots or 1.6.1 stable?

Could someone investigate?

Thanks,
Sascha

**Comment by belovictor** [comment]
No annoyance at all. Can you please make a dozen or so requests through my.openab with curl or wget to a clean and just restarted openhab and have a look if the same problem with open sockets will persist?

**Comment by digitaldan** [comment]
I'm not sure which branch I tested on, but the REST code has not changed so I don't think thats it, although I would still guess its a  atmosphere interaction issue.   @belovictor could this be related to http 1.1 and keep alives ?

**Comment by cribskip** [comment]
Mh, just now I tried several scenarios and still have a good openhab:
  - connected via 3G, toggled some switches
    - closed habdroid normally
    - disrupted 3G by disconnecting via android quick settings
  - same with wifi

and still no CLOSE_WAIT sockets... However, strangely, many "my.openhab" connections are established:
```
root@openhab:/var/www# lsof -a -i -uopenhab |grep linode.com|wc -l
43
# from lsof -a -i -uopenhab:
java    26934 openhab  168u  IPv4 121043804      0t0  TCP openhab.fritz.box:38816->li146-158.members.linode.com:https (ESTABLISHED)
java    26934 openhab  169u  IPv4 121044715      0t0  TCP openhab.fritz.box:38817->li146-158.members.linode.com:https (ESTABLISHED)
java    26934 openhab  170u  IPv4 121044716      0t0  TCP openhab.fritz.box:38818->li146-158.members.linode.com:https (ESTABLISHED)
```

I did not restart openhab as I did this already yesterday evening.

Any ideas what's happening? :-/

Thanks,
Sascha

**Comment by cribskip** [comment]
I've re-set up my setup on a fresh install and no issue like this.
New setup is on a raspberry pi 2.
