### ISSUE TITLE
openHab crashes when changing the theme

### ISSUE THREAD

**Issue by tobiasamon** [openhab/openhab.android#103]
When changing the theme and going back to the main activity an exception is thrown:

05-08 13:12:45.200: E/AndroidRuntime(17188): FATAL EXCEPTION: main
05-08 13:12:45.200: E/AndroidRuntime(17188): Process: org.openhab.habdroid, PID: 17188
05-08 13:12:45.200: E/AndroidRuntime(17188): java.lang.IllegalStateException: Fragment OpenHABWidgetListFragment{41d89718} is not currently in the FragmentManager
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.support.v4.app.FragmentManagerImpl.saveFragmentInstanceState(FragmentManager.java:603)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.support.v4.app.FragmentStatePagerAdapter.destroyItem(FragmentStatePagerAdapter.java:136)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:874)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2824)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at org.openhab.habdroid.ui.OpenHABFragmentPagerAdapter.clearFragmentList(OpenHABFragmentPagerAdapter.java:80)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at org.openhab.habdroid.ui.OpenHABMainActivity.openSitemap(OpenHABMainActivity.java:626)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at org.openhab.habdroid.ui.OpenHABMainActivity.access$400(OpenHABMainActivity.java:102)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at org.openhab.habdroid.ui.OpenHABMainActivity$5.onSuccess(OpenHABMainActivity.java:522)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:276)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:134)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.os.Looper.loop(Looper.java:136)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at android.app.ActivityThread.main(ActivityThread.java:5108)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
05-08 13:12:45.200: E/AndroidRuntime(17188): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by cribskip** [comment]
Hi,

with which version are you experiencing this? Current snapshot to playstore version?

Thanks

**Comment by tobiasamon** [comment]
Hi,

it's in the current head revision; not in play store version.

best regards
Tobias

**Comment by belovictor** [comment]
Which device/android version are you using?

**Comment by belovictor** [comment]
I was able to get this exception once today while testing another thing, but not through theme changing and going back. And since then I can't reproduce it :-O

**Comment by belovictor** [comment]
Can you please check it against the latest version from Google Play?
