### ISSUE TITLE
Support HTTPS with client certificate authentication.

### ISSUE THREAD

**Issue by slawekjaranowski** [openhab/openhab.android#109]
We can simply terminate https with client certificate authentication by haproxy or stunnel. If you wish I can show this configuration for those application.

Such configurations can be next security level for private openhab installation.
We need support for https with client certificate authentication by android application.

On android system we can import CA and personal certificate to system certificate store.  It will be good if application can use this.
##

**Comment by solucionesmipc** [comment]
hi, please show this configuration.

**Comment by slawekjaranowski** [comment]
Hi,

This is simple configuration:

```
# https with certificate requre
frontend https-cert
    bind <listen_ip:port> ssl crt <path-to-cert+key-file..pem> ca-file <path-to-CA.pem> verify required

    # require to inform backend about client real ip and about protocol
    option  forwardfor
    http-request set-header X-Forwarded-Proto https

    # replace http to https in Location header - redirect
    rspirep ^Location:\ http://(.*) Location:\ https://\1

    default_backend openhab

backend openhab
    server srv1 <openhab-ip>:8080 check inter 60000
```

**Comment by slawekjaranowski** [comment]
Hi, I've prepared new PR which takes into account comments from old PR #160 

I need to write manuals, how to configure reverse proxy and how to manage certificates.
I put file KeyAuth.md in code and in application is link to this file as help to new option.

Maybe someone want to help to write this manul.

**Comment by tulamidan** [comment]
I can help here, there are plenty of tutorials, one can be found here. If suitable I can add the missing client cert. part. https://community.openhab.org/t/using-nginx-reverse-proxy-authentication-and-https/14542/4
