### ISSUE TITLE
Remove spell correction from openHAB setting input fields

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab.android#111]
Currently my android wants to do spell correction on the openHAB URL (in settings for both for remote and normal URL) as well as the user name. If I am not careful, it even auto-corrects it. This is not necessary neither for a URL nor for the username and should be removed.

**Comment by belovictor** [comment]
This was completely unexpected and I had to switch off autocorrection on my phone. I'm currently looking into this :-)
