### ISSUE TITLE
Switch item and displayed chart do not match occasionally

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab.android#114]
Hi have this in my sitemap (very similar to the demo sitemap):
```
Frame {
	Switch item=WeatherChartPeriod label="Zeitraum" mappings=[0="Stunde", 1="Tag", 2="Woche"]
	Chart item=WeatherChart period=h refresh=30000 visibility=[WeatherChartPeriod==0]
	Chart item=WeatherChart period=D refresh=30000 visibility=[WeatherChartPeriod==1, WeatherChartPeriod=="Uninitialized"]
	Chart item=WeatherChart period=W refresh=30000 visibility=[WeatherChartPeriod==2]
}
```

Sometimes everything works as expected, sometimes the switch item and the displayed chart do not match. I wasn't yet able to figure out when exactly it is incorrect.
Sometimes, for example, the "Stunde" (hour) item is selected but the chart is displayed for the "Tag" (day):
![screenshot_2015-05-30-19-16-05 mobile](https://cloud.githubusercontent.com/assets/3878009/7898501/5c19f590-0702-11e5-94ff-84b176fa29b6.png)

**Comment by belovictor** [comment]
I guess this happens when you change the selection - the chart is not changed?

**Comment by dominicdesu** [comment]
No actually when I change the selection it works fine. It usually happened when I open the whole page - the switch item and the displayed chart do not match.
However, I haven't seen this in a while. Maybe it is related to openHAB restarts? I just wondering if it can happen that the switch item is reset to it's default on openHAb restart but the chart item is loaded from cache?

I will observe if it happens again and report more details in this case.

**Comment by belovictor** [comment]
Have you tried to have a look at this page with classicui when it happens in Android?

**Comment by dominicdesu** [comment]
I couldn't reproduce this issue for some weeks now... suggest to close this ticket, I would comment again with more details if it happens again.
