### ISSUE TITLE
habdroid: switch layout

### ISSUE THREAD

**Issue by staehler** [openhab/openhab.android#115]
Hi,
it is not quite obvious, if a switch in on or off in habdroid.
Left means switch is off, right means switch is on.
It would be nice, if it could be more obvious, eg.
left and red switch button or 0 means off
right and green switch button or 1 means on.

Kind regards,
Michael

**Comment by cribskip** [comment]
I'd really like a choice on button themes. Over the years and android firmwares I saw habdroid on, I had several "oh screw, I just looked good before the update" moments ;-)

Buttons just like [[http://ankri.de/wp-content/uploads/2012/07/switches_switches.png]] f.e. are totally fine for me, though some may found them clumsy and prefer the current "sleek style".

Regards
Sascha

**Comment by belovictor** [comment]
Well, switches of Habdroid evolve together with Android itself :-) As we don't have a dedicated designer on board to design the whole look for Habdroid, we just keep stick to default Android widgets.
