### ISSUE TITLE
Habdroid reverts Selection to "0" on refresh

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab.android#118]
reference:  https://groups.google.com/forum/#!searchin/openhab/CT100/openhab/Exf1NPI-VC4/uOYIRniYbscJ

The current build of Habdroid from CloudBees seems to behave differently than a browser with respect to the sitemap entry:

Selection item=HVAC_Mode label="HVAC mode" icon="temperature" mappings=[0="Off",1="Heating",2="Cooling",3="Auto",4="Something",5="Resume"]

When a browser is used (either Firefox or Chrome) the mode is allowed to be set without resetting, and the mode setting stays where it is set.  This is the desired result.

I looked for the difference with a network sniffer and saw that the browser simply returned the value from a GET such as GET /rest/sitemaps/jim/jims HTTP/1.1

Habdroid issues a POST immediately after the GET, without user input setting the mode to "0"
POST /rest/items/HVAC_Mode HTTP/1.1\r\n
Request URI: /rest/items/HVAC_Mode
Line-based text data: text/plain
0

This happens with simply viewing the sitemap from Habdroid, and causes the mode to always be reset to 0 which is OFF on the thermostat.  Trying to set the mode from the Habdroid at this point sets the new mode and it is immediately reversed with a POST back to HVAC_mode 0

Config file snippets below for reference.

items:

    Number HVAC_HeatSetPoint	"Heat Set [%.1f F]"   <thermostat> (ALL,HVAC)		{zwave="5:command=thermostat_setpoint,setpoint_type=1" } 
    Number HVAC_CoolSetPoint  "Cool Set [%.1f F]"   <thermostat> (ALL,HVAC) {zwave="5:command=thermostat_setpoint,setpoint_type=2" }
    Number HVAC_Temperature  "Thermostat temperature [%.1f °F]" <temperature> (ALL,HVAC,ff)	{zwave="5:1:command=sensor_multilevel,sensor_type=1,refresh_interval=60"}
    Number HVAC_Humidity		"Thermostat humidity [%.1f %%]" 	(ALL,HVAC,ff)	{zwave="5:2:command=sensor_multilevel,sensor_type=5,refresh_interval=60"}
    Number HVAC_Mode			"Mode [MAP(thermostatMode.map):%s]" (ALL,HVAC)		{zwave="5:command=thermostat_mode"}

sitemap:

		Text label=HVAC icon="temperature" {
			Setpoint item=HVAC_HeatSetPoint label="Heat setpoint" icon="temperature" minValue=50 maxValue=90 step=0.5
			Setpoint item=HVAC_CoolSetPoint label="Cool setpoint" icon="temperature" minValue=60 maxValue=90 step=0.5
			Selection item=HVAC_Mode label="HVAC mode" icon="temperature" mappings=[0="Off",1="Heating",2="Cooling",3="Auto",4="Something",5="Resume"]}

**Comment by xsnrg** [comment]
I am not terribly handy in the code but am willing to do what I can to help debug.  Any pointers would be appreciated.

Thanks

**Comment by xsnrg** [comment]
fired up the Android emulator.

06-18 11:27:27.507    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Spinner item click on index 2
06-18 11:27:27.507    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Spinner onItemSelected selected label = Cooling
06-18 11:27:27.507    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Label selected = Cooling
06-18 11:27:27.507    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Spinner onItemSelected found match with 2
06-18 11:27:32.674    2303-2303/org.openhab.habdroid V/AsyncHttpResponseHandler﹕ Progress 1246 from 1246 (100%)
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetListFrag﹕ processContent() http://192.168.1.239:8080/rest/sitemaps/test/00
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetListFrag﹕ isAdded = true
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Stopping video for 0 widgets
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Stopping image refresh for 0 widgets
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"id":"00","title":"HVAC","icon":"temperature","link":"http:\/\/192.168.1.239:8080\/rest\/sitemaps\/test\/00","parent":{"id":"test","title":"test","link":"http:\/\/192.168.1.239:8080\/rest\/sitemaps\/test\/test","leaf":false},"leaf":true,"widgets":[{"widgetId":"00_0","type":"Setpoint","label":"Heat setpoint","icon":"temperature","mappings":[],"minValue":50,"maxValue":90,"step":0.5,"widgets":[]},{"widgetId":"00_1","type":"Setpoint","label":"Cool setpoint","icon":"temperature","mappings":[],"minValue":60,"maxValue":90,"step":0.5,"widgets":[]},{"widgetId":"00_2","type":"Selection","label":"HVAC mode","icon":"temperature","mappings":[{"command":"0","label":"Off"},{"command":"1","label":"Heating"},{"command":"2","label":"Cooling"},{"command":"3","label":"Auto"},{"command":"4","label":"Something"},{"command":"5","label":"Resume"}],"widgets":[]},{"widgetId":"00_3","type":"Text","label":"HVAC_Temperature","icon":"text","mappings":[],"widgets":[]},{"widgetId":"00_4","type":"Text","label":"HVAC_Humidity","icon":"text","mappings":[],"widgets":[]},{"widgetId":"00_5","type":"Text","label":"HVAC_Fan_Mode","icon":"text","mappings":[],"widgets":[]},{"widgetId":"00_6","type":"Text","label":"HVAC_Operating_State","icon":"text","mappings":[],"widgets":[]}]}
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"widgetId":"00_0","type":"Setpoint","label":"Heat setpoint","icon":"temperature","mappings":[],"minValue":50,"maxValue":90,"step":0.5,"widgets":[]}
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"widgetId":"00_1","type":"Setpoint","label":"Cool setpoint","icon":"temperature","mappings":[],"minValue":60,"maxValue":90,"step":0.5,"widgets":[]}
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"widgetId":"00_2","type":"Selection","label":"HVAC mode","icon":"temperature","mappings":[{"command":"0","label":"Off"},{"command":"1","label":"Heating"},{"command":"2","label":"Cooling"},{"command":"3","label":"Auto"},{"command":"4","label":"Something"},{"command":"5","label":"Resume"}],"widgets":[]}
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"widgetId":"00_3","type":"Text","label":"HVAC_Temperature","icon":"text","mappings":[],"widgets":[]}
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"widgetId":"00_4","type":"Text","label":"HVAC_Humidity","icon":"text","mappings":[],"widgets":[]}
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"widgetId":"00_5","type":"Text","label":"HVAC_Fan_Mode","icon":"text","mappings":[],"widgets":[]}
06-18 11:27:32.674    2303-2303/org.openhab.habdroid D/OpenHABWidgetDataSource﹕ {"widgetId":"00_6","type":"Text","label":"HVAC_Operating_State","icon":"text","mappings":[],"widgets":[]}
06-18 11:27:32.675    2303-2303/org.openhab.habdroid I/OpenHABWidgetListFrag﹕ showPage for http://192.168.1.239:8080/rest/sitemaps/test/00 longPolling = true
06-18 11:27:32.675    2303-2303/org.openhab.habdroid D/OpenHABWidgetListFrag﹕ isAdded = true
06-18 11:27:32.675    2303-2303/org.openhab.habdroid D/OpenHABWidgetListFrag﹕ {"id":"00","title":"HVAC","icon":"temperature","link":"http://192.168.1.239:8080/rest/sitemaps/test/00","parent":{"id":"test","title":"test","link":"http://192.168.1.239:8080/rest/sitemaps/test/test","leaf":false},"leaf":true,"widgets":[{"widgetId":"00_0","type":"Setpoint","label":"Heat setpoint","icon":"temperature","mappings":[],"minValue":50,"maxValue":90,"step":0.5,"widgets":[]},{"widgetId":"00_1","type":"Setpoint","label":"Cool setpoint","icon":"temperature","mappings":[],"minValue":60,"maxValue":90,"step":0.5,"widgets":[]},{"widgetId":"00_2","type":"Selection","label":"HVAC mode","icon":"temperature","mappings":[{"command":"0","label":"Off"},{"command":"1","label":"Heating"},{"command":"2","label":"Cooling"},{"command":"3","label":"Auto"},{"command":"4","label":"Something"},{"command":"5","label":"Resume"}],"widgets":[]},{"widgetId":"00_3","type":"Text","label":"HVAC_Temperature","icon":"text","mappings":[],"widgets":[]},{"widgetId":"00_4","type":"Text","label":"HVAC_Humidity","icon":"text","mappings":[],"widgets":[]},{"widgetId":"00_5","type":"Text","label":"HVAC_Fan_Mode","icon":"text","mappings":[],"widgets":[]},{"widgetId":"00_6","type":"Text","label":"HVAC_Operating_State","icon":"text","mappings":[],"widgets":[]}]}
06-18 11:27:32.697    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Spinner item click on index 0
06-18 11:27:32.697    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Spinner onItemSelected selected label = Off
06-18 11:27:32.697    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Label selected = Off
06-18 11:27:32.697    2303-2303/org.openhab.habdroid D/OpenHABWidgetAdapter﹕ Spinner onItemSelected found match with 0


As you can see, spinner click on item 2, but at next refresh, without any clicks the Android app sets it back to 0

**Comment by xsnrg** [comment]
This can happen without any devices.  Just set up the sitemap to look like this:

sitemap test label="test"
{
		Text label=HVAC icon="temperature" {
			Setpoint item=HVAC_HeatSetPoint label="Heat setpoint" icon="temperature" minValue=50 maxValue=90 step=0.5
			Setpoint item=HVAC_CoolSetPoint label="Cool setpoint" icon="temperature" minValue=60 maxValue=90 step=0.5
			Selection item=HVAC_Mode label="HVAC mode" icon="temperature" mappings=[0="Off",1="Heating",2="Cooling",3="Auto",4="Something",5="Resume"]
			Text item=HVAC_Temperature
			Text item=HVAC_Humidity
			Text item=HVAC_Fan_Mode
			Text item=HVAC_Operating_State
		}
}

**Comment by xsnrg** [comment]
@belovictor would really like your input on this one. I have tried using breakpoints in the Android IDE, but am not finding what is happening yet.

**Comment by xsnrg** [comment]
I created the simple sitemap:

sitemap test
{
	Frame {
		Text label=Test icon="temperature" {
		Selection item=FakeMode label="Fake mode" icon="temperature" mappings=[0="Off",1="Heating",2="Cooling",3="Auto"]
		}
}

I then set a breakpoint at line 330 of /OpenHABWidgetListFragment.java, and stepped through.  I wasn't able to see exactly when it changed back, but it seems to be somewhere in the long polling.

I know the code that sets the new value in the item works, because in the case of my thermostat, it sets it to cooling and the quickly sets it back to off.  This happens whether there actually is a corresponding item or not.  In the case of this fake sitemap, the corresponding item does not exist.  In the case of my actual sitemap, my thermostat exists and is affected.

**Comment by belovictor** [comment]
Looks like it issues the first command from the list if the current status is undefined. I'll look into this today in the evening.

**Comment by xsnrg** [comment]
It may be related, so will mention it here, but Setpoint has a very similar problem.  Setting a new Setpoint immediately reverts back to the previous setting.

**Comment by belovictor** [comment]
Does your setpoint have a corresponding valid item?

**Comment by belovictor** [comment]
Ok, so everything is fine with openHAB 1.x, the problem only exists with openHAB 2.x. The source of the problem is that uninitialized statuses of items used to be 'Uninitialized' in 1.x and in 2.0 @kaikreuzer made them NULL instead :-) I'm thinking now on how to fix that, cause the part of the app which processes this is really not cared about openHAB version...

**Comment by xsnrg** [comment]
Hi Victor, my Setpoint does have a corresponding item.  I am using a z-wave thermostat.  The settings are read and displayed correctly in the Android app, but when I try to change one, it shows the change briefly, and then reverts back to the initial setting without any additional key press.  I have not tried a setpoint that is not tied to an actual item yet.

Jim

**Comment by kaikreuzer** [comment]
> I'm thinking now on how to fix that, cause the part of the app which processes this is really not cared about openHAB version...

Could you simply treat NULL and Uninitialized both always the same way? (btw, it was @teichsta's suggestion https://github.com/openhab/openhab2/issues/186#issuecomment-93312843 :-) )

**Comment by xsnrg** [comment]
Victor, thanks for the work.  Unfortunately, it has not fully solved the issue.  I grabbed the new debug.apk from cloudbees after I verified it was built with the new commit, but it is still acting nearly the same.  I have tried it on two different thermostats.  Please re-open.

How can I help you debug?

Thanks
Jim

**Comment by xsnrg** [comment]
It looks like I was wrong.  After testing it a bit more, there is a new behaviour.  The mode looks like it is getting set correctly, and staying.  It is the displaying of the Selection that reverts to the first item in the list, but the actual setting behind the scenes appears to be sticking, so the worst problem is indeed fixed.

![screenshot_2015-06-23-07-30-40](https://cloud.githubusercontent.com/assets/1186921/8306021/0cb9759a-197a-11e5-8651-8eab5cd4b969.png)

**Comment by xsnrg** [comment]
The web interface does show "Cooling" which is the correct Selection while showing "Cool" which is the correct mode.  

I will open a new ticket for the setpoint issue.

**Comment by xsnrg** [comment]
@kaikreuzer @belovictor  This is still causing problems for me.  On a thermostat, 0=off for the mode, and since it always defaults to showing "off" or 0 in the code, it doesn't ever sense an update and I cannot turn the HVAC off with HABDroid.  The fan is the same way, I cannot select "on" in position 0.

Do we re-open this issue, or start a new one?

![off](https://cloud.githubusercontent.com/assets/1186921/9017374/1c8b61dc-379c-11e5-87dc-c00e6c42218b.png)

**Comment by digitaldan** [comment]
Is this still a valid issue?  I have been testing with OH2 and I cannot reproduce the issue.

**Comment by xsnrg** [comment]
This seems to have changed/been fixed somewhere along the way, so likely in the ESH realm.  At any rate, will close.
