### ISSUE TITLE
HABDroid is not respecting the user URL when making rest calls

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab.android#122]
I am happy enough with OpenHab2 now to start really using it for my house.  Part of using it is to use it remotely just as I would on my LAN.  I realize the security parts are not there yet, so I decided to do a secured reverse proxy to the ssl port.

With reverse proxy, I now have the OH2 web interface asking for a password, using SSL, allowing login, and once authenticated, everything I have tried so far seems to work with a web browser.

I am trying to use habdroid to hit the same URL, and am watching the logs.  I believe there is a bug in habdroid  where it does not respect the remote URL completely.  For the rest calls, it should still be requesting the full URL as the base of the rest request, and it is truncating it.

For example:

If I have my reverse proxy set up to send "H" to 8443, then the browser request would look like this:  https://website.here/H and the reverse proxy picks up on H and passes it to 8443

With Habdroid, I am seeing the initial request hit "H" as defined in the settings, but subsequent requests to the API are just coming in https://website.here/rest instead of https://website.here/H/rest.

A little more from the logs:
 
/H/rest/bindings is requested first, 200.
/H/rest/sitemaps is requested next, 200.
/rest/sitemaps/sitemap is requested next, 404.  Could be the API sending the base URL back too.

Jim

**Comment by belovictor** [comment]
This is not a bug in HABDroid. First request to '/H/rest/bindings' is used to detect if this is OH 1.x or 2.x.
The second request to '/H/rest/sitemaps' is done to get list of available sitemaps. From that point HABdroid will be using URLs provided in sitemap data which it got from '/H/rest/sitemaps'. If you request this URL from your browser you will see this data is pointing to 'rest/sitemaps/sitemap' because openHAB doesn't support URL translation.

**Comment by xsnrg** [comment]
Ugh.  understood.  Makes securing it before security gets baked in to be a bit more difficult then.  Thanks for the explanation.

**Comment by belovictor** [comment]
You can setup a dedicated port instead of Path, it should work then!

**Comment by xsnrg** [comment]
Good call.  I had not thought through it yet, you just saved me some time!
