### ISSUE TITLE
Notification time not localized

### ISSUE THREAD

**Issue by dmcwhinnie** [openhab/openhab.android#126]
When notifications are displayed on the Android client, they are not displaying the local time.  I am in Central time, and the notification shows the message time as "in 4 hours, 1:50am".  My time is 9:50pm.  Would be nice if the time was either the local Openhab time, or the android device time.

**Comment by belovictor** [comment]
Do you mean notifications list from the drawer menu inside the app?

**Comment by dmcwhinnie** [comment]
Yes that is correct. Inside the app.

**Comment by frode** [comment]
I can confirm this issue

**Comment by sihui62** [comment]
I also can confirm this issue, in my case the notifications are alway at UTC.

Siegfried
