### ISSUE TITLE
Missing icons are filled up with a lot of whitespace

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab.android#130]
Displayed items without an icon assigned have too much whitespace in latest HABdroid (taken directly from GIT repository):

![screenshot_2015-08-03-22-15-03](https://cloud.githubusercontent.com/assets/3878009/9046836/d19219ca-3a2d-11e5-95c4-ded846076ac2.png)

Using a Nexus 4.

**Comment by belovictor** [comment]
This is a bug, cause height of the cells should be fixed.

**Comment by dominicdesu** [comment]
@belovictor I think I could provide a solution if you haven't already fixed this?

**Comment by belovictor** [comment]
That would be nice! What the solution is?

**Comment by dominicdesu** [comment]
One possibility which fixes the issue on my device is to set the layout_width and layout_height of the MySmartImageView layout to fixed 50dip and remove the min/max Width/Height declarations, like this:
```
<org.openhab.habdroid.util.MySmartImageView
    android:paddingTop="6dip"
    android:paddingBottom="6dip"
    android:layout_width="50dip"
    android:layout_height="50dip"
    android:id="@+id/widgetimage"
    android:layout_gravity="center_vertical" />
```

However I would like to investigate if there is a "better" solution.

Also, I don't understand why this only happens for items "without" icons. As these items actually have a blank icon which is the same size as all the other icons, it should be just the same...

**Comment by belovictor** [comment]
Any news on that?

**Comment by dominicdesu** [comment]
Sorry for the delay... I will try to make a pull request in the next few days. Is there any deadline this week already?
