### ISSUE TITLE
Every other (alternating) voice commands will fail

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab.android#132]
I have been playing a lot with voice commands with the current version of HABDroid and OpenHAB2 over the last few days.  I have found that the Android App will fail on alternating voice commands.  The first one will work fine, the second one will fail with a "Didn't catch that.  Try again" message.  The same utterance on the next attempt will work fine.  This is repeatable nearly 100% of the time.

Jim

**Comment by dominicdesu** [comment]
Do you have the chance to test this with another android device? HABdroid should only use and retrieve the resulting text from the voice recognition service of Android/Google. Doesn't sound like this is a problem in HABdroid...

**Comment by xsnrg** [comment]
I have tried on a nexus 9 now, and it seems to work better.  Guess I will try rebooting the phone to see if it helps.  The phone is a Galaxy 5 if anyone is curious.

**Comment by xsnrg** [comment]
Closing.  After rebooting the phone it works better.
