### ISSUE TITLE
HABDroid reloads/refreshes a few seconds after application start

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab.android#134]
When starting HABDroid on my Samsung Galaxy S4 (Android 5.0.1) the first page reloads/refreshes after a few seconds. This is extremely annoying as I need to wait a few seconds before trying to do something. If I start the app and immediately click on e.g. "Ground floor" and then "Bedroom", the app reloads the first page before I manage to e.g. turn a light on, and I have to again click on "Ground floor" and "Bedroom" ...

I do not see the same issue on my Galaxy Tab.

I'm happy to send a video of the problem if that helps :)

**Comment by belovictor** [comment]
Yep, a video would help much to understand the problem.

**Comment by anordvall** [comment]
Sure! I've uploaded two videos:

http://tp.se/habdroid/reload%20issue%201.mp4
http://tp.se/habdroid/reload%20issue%202.mp4

I'm using a Galaxy S4 with Android 5.0.1

**Comment by belovictor** [comment]
Well, this refresh just means openHAB told Android app that something changed on this page, it's definitely not a bug in the app.
