### ISSUE TITLE
Button (switch with mapping) reacts to button down rather than to button up

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab.android#135]
Buttons etc in the HABDroid UI correctly reacts to button up (release) events, with one exception; When a switch has a mapping (i.e. making it a button) it triggers as soon as you press down on it. This makes it hard to scroll in the UI as you need to make sure you don't press down on one of these switches when you start scrolling.

**Comment by belovictor** [comment]
Hmm, button should not react on press when an overlay scroll gesture is detected by Android. Which device/android version are you using?

**Comment by anordvall** [comment]
To clarify, you don't need to start scrolling either. Just press down on a button and it will immediately act on it before you even lift your finger. The problem is that you might want to just scroll, and not actually act on the button. Note that this behavior only exists for buttons (not normal switches).

I uploaded a video to:
http://tp.se/habdroid/button%20down%20issue.mp4

I'm using a Galaxy S4 with Android 5.0.1

Hope it helps :)
