### ISSUE TITLE
grey notification icon

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab.android#140]
I think the notification icon should be grey like most apps do nowadays.

![openhab_colored_notification_icon](https://cloud.githubusercontent.com/assets/1270359/10560933/c9233fb8-7519-11e5-820b-8c63d8b2be7d.jpg)

**Comment by belovictor** [comment]
Would be great if you draw one!

**Comment by CWempe** [comment]
Lucky me.
I found a icon generator for this. :)
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html

I cannot append the zip file here, but you can generate the files yourself.

I used this image to start with:
http://www.openhab.org/assets/images/openhab-logo-square.png
