### ISSUE TITLE
Group item rollershutter error

### ISSUE THREAD

**Issue by belovictor** [openhab/openhab.android#141]
https://github.com/openhab/openhab/issues/2014

**Comment by rmichalak** [comment]
Some time ago I started topic on google groups about this problem: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openhab/pdLHhjH8dBE/9xt2wUV5fUkJ but nobody responded. I implemented this in my local environment and it works fine. I can create patch for both openhab and openhab.android repositories, just let me know if it is OK to introduce this kind of change in openhab REST API. Quick look at OH2 REST API code makes me think that the same problem is there, but I have not tried it though.

**Comment by gnalbandian** [comment]
I am experiencing the same issue.
It would be nice to have this commited.
Thanks for the fix.
Regards.

**Comment by digitaldan** [comment]
Close via #165
