### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by gerdesj** [openhab/openhab.android#149]
I have OpenHAB behind a HAProxy (1.5) for SSL offloading.  HABDroid fails to connect through the proxy and I simply get "SSL handshake errors" in the haproxy log. These work:

* Connection from the same mobile/cell via a browser
* Connection direct to the RasPi from HABDroid, bypassing HAProxy

The only thing I can think of that might cause problems is that my SSL cert is a wildcard job ie cn=*.domain.co.uk.  I have tried turning on and off the various ignore SSL problems options in HABDroid.

**Comment by slawekjaranowski** [comment]
It should work - I use simmilar configuration without problem.
Do you have self signed certificate?

**Comment by digitaldan** [comment]
Is this still valid with the latest release?

**Comment by gerdesj** [comment]
I'm going to close this.  No one else seems to have a similar problem and an awful lot has changed in the meantime (OHAB, HAProxy, Raspian etc.) so this issue is probably irrelevant nowadays.

Thanks for taking the trouble for checking.
