### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by mgarciate** [openhab/openhab.android#151]
I checked this app supports German, French, Flemish but not Spanish. I'm not a professional translator but nevertheless as a Spanish native developer I might set a good approach.
##

**Comment by digitaldan** [comment]
I agree!

**Comment by mueller-ma** [comment]
@mgarciate @digitaldan This can be achieved very easily: Copy https://github.com/openhab/openhab.android/blob/master/mobile/src/main/res/values/strings.xml to /mobile/src/main/res/values-es/strings.xml and translate only the words between `<string name="xxxxxx">` and `</string>`. Make a PR and I will be accepted

**Comment by mgarciate** [comment]
Hi @mueller-ma, I already did it a couple weeks ago. PR #234

**Comment by mueller-ma** [comment]
@mgarciate Can you close this issue?

**Comment by mgarciate** [comment]
Sure
