### ISSUE TITLE
Critical security issue: App is not using SSL (https) URLs! 

### ISSUE THREAD

**Issue by SoftXperience** [openhab/openhab.android#152]
I have configured a remote URL using https protocol. But the app is still using the unencrypted http url! 

I discovered it as I turned off port 80 http on my server: the app isn't working anymore. Also I can see the http URLs in Android log and with proxying the requests.

I tested a bit and found out the the server REST API also delivers the http URLs although requested via https. So maybe this is not an issue of the app, but the server.

Didn't have time to dig into the API core of openhab to check it.

Or did I miss a setting on server side?

**Comment by SoftXperience** [comment]
Ok, seems to be a problem with apache reverse proxy. I proxy my https to the http port of openhab, so it returns http, I guess.

**Comment by JensErat** [comment]
Just hit the same problem. The reverse proxy redirects HTTP to HTTPs, but somehow Habdroid always tries HTTP again when doing some operations (fetching images, POSTing changes, ... -- loading sitemaps works fine). This is very unexpected behavior, and I propose to reopen and further investigate the issue.

**Comment by SoftXperience** [comment]
The problem is that the reverse proxy connects to openhab with http. So it responds with http.
I have resolved the issue (if I remember correctly) by configuring openhab to use https with a self signed certificate (like described in the wiki). The server name must be the same like the server name you use from outside. Then imported that self signed certificate to the machine, so that the reverse proxy accepts it. Then let the reverse proxy connect to openhab via https instead of http. It returns and uses the correct https URLs then.
My Apache config then uses a Let's Encrypt certificate for connections from outside.
Let me know if you need further informations.

**Comment by SoftXperience** [comment]
Browser <-- Let's Encrypt --> Apache Reverse Proxy <-- Self signed --> openhab

**Comment by JensErat** [comment]
Digging deeper, I realized all that needs to be done is setting up another HTTP header:

    proxy_set_header X-Forwarded-Proto $scheme;

This will make Jetty make OpenHAB think HTTPs was used (or something similar, not quite sure what happens behind the scenes).

So this might "not really" be a Habdroid issue, although Habdroid might have a better problem handling here (indicate endless HTTP forwards, warn about HTTP redirection, ...).
