### ISSUE TITLE
Error when try to compile

### ISSUE THREAD

**Issue by fariz** [openhab/openhab.android#155]
i have error when want to compile it source code, help please
![error openhab](https://cloud.githubusercontent.com/assets/65761/13695128/34299e4c-e78e-11e5-8f91-6e5826995eff.png)

**Comment by CristianSarac** [comment]
In your build.gradle you have to enable multidex 
`multiDexEnabled true

compile 'com.android.support:multidex:'`

**Comment by digitaldan** [comment]
see #158
