### ISSUE TITLE
Links are not rendered properly

### ISSUE THREAD

**Issue by macmeck** [openhab/openhab.android#163]
I have set up links between my sitemaps as simple items such as

`String linkSitemapDefault "<a href='/openhab.app?sitemap=default'>Home</a>"`

The Web UI renders these items quite nice and I can navigate from sitemap to sitemap. The android app just displays the text of the link (incl. the `<a href=...>` tag) and does not even jump to the linked page.

**Comment by watou** [comment]
While useful, I don't think embedding HTML in item labels is a supported feature (and the Android app isn't a web browser). I think this could be a useful capability in Eclipse SmartHome to have links to other sitemaps and might be something for the ESH forum?

**Comment by macmeck** [comment]
Well it works in the current openhab implementation and the solution was suggested in a discussion forum some time ago. Switching between frames also works fine on the Android app so I don't see why links between sitemaps should not be possible on the app.

**Comment by watou** [comment]
@macmeck I'm not arguing against whether the feature should exist; I'm only pointing out that it's only possible in the web client because the label text is being interpreted as HTML tags, which is really just an accidental by-product of that client running in a web browser.  A new feature would have to exist and be supported by clients, which at this stage would be a discussion for Eclipse SmartHome.

**Comment by lolodomo** [comment]
To switch between sitemaps, HABdroid provides a menu at top left for that. That's a very good idea.

**Comment by digitaldan** [comment]
>I'm only pointing out that it's only possible in the web client because the label text is being interpreted as HTML tags, which is really just an accidental by-product of that client running in a web browser. A new feature would have to exist and be supported by clients, which at this stage would be a discussion for Eclipse SmartHome.

I completely agree,  I'm going to close this,  thanks.
