### ISSUE TITLE
Add and update license headers on source code

### ISSUE THREAD

**Issue by watou** [openhab/openhab.android#164]
Hi, @belovictor, I looked around this repo for license terms and didn't find any.  [Here](https://github.com/openhab/openhab.android/issues/30#issuecomment-89191827) you said that "openHAB is published under Eclipse Public License" but I did not see evidence of that in this particular repo.  The reason I ask is that, without an explicit license, others may take your (and contributors') excellent work and derive closed source, for-profit works, or others may decide not to use the app due to the absence of license terms.  Thanks in advance for your perspective.

**Comment by kaikreuzer** [comment]
@watou The license for this repo is right in its root, where it belongs: https://github.com/openhab/openhab.android/blob/master/LICENSE

> without an explicit license, others may take your (and contributors') excellent work and derive closed source

This is completely wrong - without a license, others are not granted ANY rights to use the code at all - the full copyright of the authors apply.

**Comment by watou** [comment]
>> without an explicit license, others may take your (and contributors') excellent work and derive closed source

> This is completely wrong - without a license, others are not granted ANY rights to use the code at all - the full copyright of the authors apply.

What I mean is that others may wrongly believe that they may do so, since the absence of a license on published source code may be taken as indifference by the copyright holders.  I recommend that the true terms of the source code be prominently displayed as is done in other openHAB repos, for the purpose of clarifying for those who might wish to use, contribute to, or derive works from it (or take the repo private, since no one would know its terms of use).

**Comment by kaikreuzer** [comment]
> I did not see evidence of that in this particular repo

Just randomly looking at some file, the sources even seem to have a license header: https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/core/ConnectivityChangeReceiver.java#L5
So what more do you expect exactly?

> others may take your (and contributors') excellent work

This is actually something that would be the best that can happen - as long as they do the further maintainance in this repo.
Note that Victors last activity on this code was in October 2015, we have many pending PRs and even more issues that never have been looked at in any way.
I think we need to find anyone willing to again take the lead on this project (and for iOS the same way), so that at least community contributions are respected and incorporated. Any idea how we could find such maintainers?

**Comment by watou** [comment]
> Just randomly looking at some file, the sources even seem to have a license header:

I randomly looked at a few source files and found the opposite:
https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/model/OpenHABBinding.java (for one, but the 3 Java files I looked at had no license info at all.)

> This is actually something that would be the best that can happen

Yes, as long as the license is respected.

> Any idea how we could find such maintainers?

Advertise on the community forum, just in case there is someone with the ability and interest who only needs encouragement to submit PRs.  I will think about it some more.

**Comment by CristianSarac** [comment]
>Any idea how we could find such maintainers?

@kaikreuzer Are there any requierments that need to be meet so that someone can be considered for this role ?

**Comment by kaikreuzer** [comment]
@CristianSarac The general way to become a maintainer is explained [here](https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md#how-can-i-become-a-maintainer).
For HABDroid, a good knowledge about Android app development would be very helpful :-)
Would you be interested in helping out? That would be terrific. Best thing to start would probably to help reviewing PRs from others (besides providing fixes what you have already done - thanks!)

**Comment by kaikreuzer** [comment]
@watou Ok, I have updated the issue title and re-opened the issue accordingly.

I suggest that all source files should have a license header similar to [this one](https://github.com/kaikreuzer/openhab2-addons/blob/license/src/etc/header.txt) - it would be good if this could be automated just like in the other repos through a `mvn license:format`.

**Comment by watou** [comment]
Thanks @kaikreuzer.

**Comment by CristianSarac** [comment]
@kaikreuzer  Yeah i will happy to help out. After the Easter holiday i will Start looking at the PRs. and  probably finish some of the stuff i am working right now.

**Comment by kaikreuzer** [comment]
Cool, many thanks in advance, @CristianSarac!
