### ISSUE TITLE
Support for black/AMOLED theme

### ISSUE THREAD

**Issue by zacharyyy** [openhab/openhab.android#170]
Support black/AMOLED theme to hopefully reduce battery consumption and be easier on the eyes at night. Also, some code cleanup 😄 

I have code ready for a pull request but I wanted to start a discussion first as this is my first contribution. I've been a full-time Android developer for a few years now and started using this app over the last couple months. After looking over the codebase I saw areas for improvement that I want to help with. This was the first small(ish) thing I wanted to do.

The changes I have staged and ready for submitting are:
- adding support for black/AMOLED (existing themes are exactly the same)
- replaced hamburger/menu icon with proper material design icon and animated it
- added toolbar and back navigation to info page
- added toolbar and back navigation to settings page
- cleaned up themes, strings, and unused imports
- replaced usage of a couple deprecated APIs
- cleaned up main activity on create to be more readable and idiomatic
- formatted the files that I touched to be standard for android

I love the app (and openHAB in general) and I would love to help out.

Let me know if it's okay that I submit a pull request!

Thanks,
Zach

**Comment by watou** [comment]
Zach, thank you!  That sounds like a very impressive list of improvements.

**Comment by kaikreuzer** [comment]
@zacharyyy Great to have you as an experienced Android developer on board - I am very much looking forward to your PR with those changes!

**Comment by CristianSarac** [comment]
@zacharyyy Glad to have you on board
Regarding adding a toolbar to the info page check out issue #85 
And i think that you should split your changes in different PR so that it would be more easy to backtrack(in case of disasters) and it would be much easier to review your changes

**Comment by digitaldan** [comment]
@zacharyyy  that all sounds awesome, can't wait to see your PR ;-)

**Comment by zacharyyy** [comment]
Thanks guys!

Embarrassingly, this is my first time contributing to a repo I don't own on Github. I read the contribution guidelines and I think I got it done right. I've been using Gerrit and Stash for far too long now.

The pull request is up so if you get a chance, please take a look and let me know if I need to change anything.

**Comment by zacharyyy** [comment]
Change was merged. Closing this out
