### ISSUE TITLE
Lint errors causes build failure

### ISSUE THREAD

**Issue by hazzeh** [openhab/openhab.android#171]
When building with "gradlew build". There are some new lint errors.

1. 
A removed activity is still present in the manifest. OpenHABInfoActivity which was changed to a fragment in #161.

2. 
The log TAG exceeds 23 characters. There is a new lint rule that checks for long log tags to comply with the log api: http://developer.android.com/reference/android/util/Log.html.

1 can be corrected by removing the entry from the manifest. In the same time maybe changing the log tag to current class name?

2 can be "solved" by adding
lintOptions {disable 'LongLogTag'} to build.gradle.
But imo it is better to fix the root cause of the problem: Shortening the log tag. 
The following two classes have to long log tag:
ConnectivityChangeReceiver and NotificationDeletedBroadcastReceiver

Any suggestions how to shorten the tag (or class as well)?

On another note. There is a lot of classes prepended with OpenHAB, that can be shortened to OH to save some characters ;-)

**Comment by digitaldan** [comment]
Thanks, since you have a solution for 1 and 2, would you like to do a PR? ;-)   I will look at it shortly if not.   I also need to get the cloudbee build system going to catch some of this stuff.

**Comment by hazzeh** [comment]
Sure. I'll have a PR ready soon. 
If https://wiki.jenkins-ci.org/display/JENKINS/Android+Lint+Plugin is available in cloudbees it easy to catch it.
