### ISSUE TITLE
how to give a option for user customization profiles in openhab android application?

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab.android#183]
Hello,
I am trying to develop the openhab android application. In openhab android application we will provide a option for  user customization.The user creating and saving the profiles in local database.The user profiles like Home,Away,Day,Night. After Creating the profiles user wants to select the items like Light,Fan,.etc and saved under user creating profiles . The user selected items  should be activated while click the ON button at that time itself.How to do ?
Thanks & Regards
Amar.

**Comment by digitaldan** [comment]
@amarpulli544 , are you referring to our Android app or is this a new one you are developing?

**Comment by amarpulli544** [comment]
Hello,
I am developing the user customization profiles in our android application only. In our android application,we will give options for creating a user customization profiles .We will providing a ON and OFF button and save button .After creating a profiles user wants to select the items and save under user creating profiles , while  click the save button.When the user click the profile button it will open a sitemap page and user select the items.User what ever selected items  unable to activate at the time just only save under user creating profiles.The user wants to click the ON or OFF button at that time only activating the what ever user selected items.How to do this kind of developing in our android application.
Thanks &  Regards,
Amar.

**Comment by digitaldan** [comment]
I'm not sure I understand what you are trying to do, are you trying to activate multiple items with a single button?   This sounds like it should be done inside openhab with items and groups, maybe a rule, but not a modification to the android app itself.

**Comment by amarpulli544** [comment]
Hello,
We are giving the option i.e user customization profiles for user.This sound like it should be done in your android application.like giving the below screen shots
![screenshot_2016-05-26-17-24-57](https://cloud.githubusercontent.com/assets/16384828/15598396/7b47a1f2-23f7-11e6-8062-146816093a71.png)
In this screen shot when user click the user profiles symbol it will go to the add profiles activity layout like below screen shot
![screenshot_2016-05-26-17-25-15](https://cloud.githubusercontent.com/assets/16384828/15598474/188248d2-23f8-11e6-984f-0b50a4bc5297.png)
Here the click the Add Profiles button it will go to the "Enter your profiles" like below screen shot
![screenshot_2016-05-26-17-25-29](https://cloud.githubusercontent.com/assets/16384828/15598492/715f83b6-23f8-11e6-830a-3c2a342b4fdd.png)
In this screen shot user creating the profile like Home,Away,Day,Night,etc.Here creating user profiles displaying on the add profiles layout like
![screenshot_2016-05-26-17-25-15](https://cloud.githubusercontent.com/assets/16384828/15598545/d65c62b6-23f8-11e6-96fa-481bd4a763b3.png)
The user click the profiles button it will open a sitemap layout and  user select items like fan,light ,etc.
User what ever select items saved under along with their user creating profiles.When the user click the ON or OFF button ,what ever selected should be activate at that time.The user selected items should not reflect in the main demo sitemap and items.
Thanks & Regards,
Amar.

**Comment by digitaldan** [comment]
Hi Amar, you have another issue open on this. So I'm closing this one.
