### ISSUE TITLE
HABDroid crashing on group widget with slider (dimmer) items

### ISSUE THREAD

**Issue by davorf** [openhab/openhab.android#185]
Since the last update opening a group widget, which contains few dimmer items makes HABDroid stop responding, and after a few seconds it just hangs with "Unfortunately, openHAB has stopped" message. After investigating an issue a bit more, I've found out that it hangs only if some of the lights/sliders are on. I haven't changed items nor sitemaps for at least a year, and the last version of HABDroid haven't had a problem with this or any other group widget. I forgot to add that I've already tried to reinstall the app, clear data and cache, and it didn't help. This is the part of the sitemap (group widget) that causes HABDroid to hang upon opening (while some of the lights are on):

```
		Group label="Svjetla" icon="slider" {
			Slider item=Dimmers label="Sva svjetla" icon="slider" switchSupport			
			Slider item=LivingRoom_Dimmer_MainLight label="Dnevna soba - glavno svjetlo" icon="slider" switchSupport			
			Slider item=LivingRoom_Dimmer_Lamp label="Dnevna soba - lampa" icon="slider" switchSupport			
			Slider item=Bedroom_Dimmer_MainLight label="Spavaća soba - glavno svjetlo" icon="slider" switchSupport			
			Slider item=Kitchen_Dimmer_MainLight label="Kuhinja - glavno svjetlo" icon="slider" switchSupport			
			Slider item=Hallway_Dimmer_MainLight label="Hodnik - glavno svjetlo" icon="slider" switchSupport			
		}	
```

I've attached a screenshot of the problematic group item as well.

![2016-05-27 07 21 03](https://cloud.githubusercontent.com/assets/19305218/15600801/8f8743a8-23ec-11e6-9cee-e4526d3a444f.png)

**Comment by therealtobo** [comment]
Same here with the following sitemap:

```
                Text    label="Media" icon="video"      {
                        Frame   label="Livingroom TV" {
                                Switch  item=LivingTV_Power label="Power" icon=""
                                Switch  item=LivingRC_Input mappings=[19="HTPC", 20="PS4", 10="ChromeCast"] label="" icon=""
                                Switch  item=LivingRC_Vol icon="" label="Volume" mappings=[DECREASE="-", INCREASE="+"]
                                Switch  item=LivingRC_Mute label="Mute" icon=""
                              Slider  item=LivingRC_Vol
                        }
                        Frame   label="Familyroom TV" {
                                Switch  item=FamilyTV_Power label="Power" icon=""
                                Switch  item=FamilyRC_Input mappings=[25="HTPC", 21="PS4", 06="ChromeCast"] label="" icon=""
                                Switch  item=FamilyRC_Vol icon="" label="Volume" mappings=[DECREASE="-", INCREASE="+"]
                                Switch  item=FamilyRC_Mute label="Mute" icon=""
                              Slider  item=FamilyRC_Vol
```
               }

If I remove the sliders, the page loads fine, otherwise it does what @davorf is stating, starts a "window scroll", pauses and then crashes. Started when upgrading to the latest HabDroid without any other changes.

**Comment by digitaldan** [comment]
Thanks guys, that really helps, I'll take a look this weekend.

**Comment by digitaldan** [comment]
Hmm, I have tried this on both OH1 and OH2 and not been able to reproduce.  I'm assuming this is openhab 1.8.x ?  It would be helpful to see what's being returned in the sitemap rest request, can you use your browser to request your sitemap, like "http://yourserver:8080/rest/sitemaps/demo", except replace demo with the sitemap name, and post here or send to  dan@digitaldan.com (if that's more comfortable)  ?

**Comment by therealtobo** [comment]
For me it's on OH2b2 and OH2b3, same issue. I've gotten the info from the page you requested but feel I need to go through it before sending, a lot of possibly sensitive data there. If needed I'll do it but with the above sitemap and also the following things, it should be enough?

Dimmer  LivingRC_Vol            "Livingroom volume"     <receiver>      (Ground_Living,Video,Control_LR)

Basically, is there any other information to retrieve? It's a pioneeravr item by the way since it's not displayed in the items file for OH2 (configured using paper).

**Comment by digitaldan** [comment]
@therealtobo , if you can navigate to just the leaf that contains that group/section , like "/rest/sitemaps/main/0000010001" , you could just post that one part.  I'm interested in knowing what state description and pattern is being returned.

**Comment by digitaldan** [comment]
Also if anyone has the ability to get a netcat log when it crashes, that would certainly help!

**Comment by therealtobo** [comment]
For me it's no group but maybe a section then? I'll have a look.

**Comment by davorf** [comment]
@digitaldan I've sent you an e-mail with with sitemap XML. Regarding netcat log, I'm not sure what that is. If you could please elaborate, I'm willing to do it.

Best regards,
Davor

**Comment by therealtobo** [comment]
@digitaldan Did you get what you needed or should I try to get some outtakes from the page you mentioned above as well?

**Comment by digitaldan** [comment]
@davorf logcat is a tool that comes with the android sdk, it allows you to see all the logs from an android device.  I found a little tutorial on how to install and run the logcat tool here http://forum.xda-developers.com/showthread.php?t=2274119 , while logcat is running crash the app and post or email me the relevant part log file (lines will have opnehab in them) .  I'm still trying to recreate on my side in the meantime. 

@therealtobo short of a logcat file, I'm not sure what else would help right now. I'm trying to get access to our hosted log crash tool, not sure if this would show up there.

**Comment by digitaldan** [comment]
Hi all, I have a fix I'm just testing out now, stay tuned.

**Comment by digitaldan** [comment]
I will push the fix out today to the play store, if others want to test there's a signed APK here https://github.com/digitaldan/openhab.android/releases/tag/1.8.1

**Comment by digitaldan** [comment]
This has been pushed out to the play store, if the issue persists feel free to reopen , thanks!

**Comment by rvfh** [comment]
Maybe my issue is different, but version 1.8.0.1 does not fix the crash I have when my dimmer value is set to UNDEF...

**Comment by digitaldan** [comment]
@rvfh I'll reopen and take a look

**Comment by rvfh** [comment]
Adding a logcat. Let me know if you want me to test things...
[logcat.txt.gz](https://github.com/openhab/openhab.android/files/299345/logcat.txt.gz)

**Comment by rvfh** [comment]
My wild guess if that in OpenHABWidgetAdapter.java at line 447 you may want something like:
`if (openHABWidget.getItem().getState() == null)`
`sliderSeekBar.setProgress(0);`
`else`
`sliderSeekBar.setProgress(openHABWidget.getItem().getStateAsFloat().intValue());`

**Comment by digitaldan** [comment]
I have PR #192 to address this, testing now.

**Comment by digitaldan** [comment]
If you could install https://github.com/digitaldan/openhab.android/releases/tag/1.8.0.2 and test that would be great, thanks !

**Comment by rvfh** [comment]
This fixes it for me :+1: Great job!

**Comment by digitaldan** [comment]
Deployed in 1.8.0.2
