### ISSUE TITLE
How to access default the sitemaps and items when clicking the user creating profiles?

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab.android#186]
Hello,
I did done the giving option for user creating profiles in your Openhab android application.But don't know how to access default the sitemaps and items when clicking the user creating profiles in your openhab android application.We are giving the below screen shot along with user customization profiles requirements.
In below screen shot I creating the user profile icon.
![screenshot_2016-05-26-17-24-57](https://cloud.githubusercontent.com/assets/16384828/15777997/ff9c653c-29b0-11e6-815d-72bc703ec162.png)
When user click the user icon it will open a Add Profiles page like below screen shot
![screenshot_2016-05-26-17-25-15](https://cloud.githubusercontent.com/assets/16384828/15778047/5c750b9c-29b1-11e6-92dd-20757799beff.png)
The user here click the Add Profiles button it will open "entering your profiles" page like below screen shot
![screenshot_2016-05-26-17-25-29](https://cloud.githubusercontent.com/assets/16384828/15778103/b94d82ea-29b1-11e6-9730-a9940ab81989.png)
Here user creating the profiles and save it .The saving profiles visible in Add Profiles page like below screen shot
![screenshot_2016-05-26-17-25-15](https://cloud.githubusercontent.com/assets/16384828/15778157/0b7a3dba-29b2-11e6-837c-ffc89f53d221.png)
When the user click the profile it will open default sitemap.In your android source code,where the storing the default sitemap then how to access the default sitemap.
Thanks & Regards,
Amar.

**Comment by digitaldan** [comment]
I'm not sure what you are trying to do.  What is a user profile? how is this different from selecting a sitemap in the sidebar menu?
