### ISSUE TITLE
HABdroid discovery: scroll not working well

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#190]
openHAB server 2.0 beta 3
HABdroid 1.8.0.1

When selecting Discovery from the main menu, you get a list of discovered things. If you have a lot of things, scrolling is not working well.
##

**Comment by digitaldan** [comment]
I have actually not played with the disc part of android yet, I'll give it a try soon.

**Comment by digitaldan** [comment]
indeed, it keeps trying to refresh instead of scroll for me, I will take a look.

**Comment by lolodomo** [comment]
Yes exactly

**Comment by lolodomo** [comment]
As this windows has been suppressed, I close the issue.
