### ISSUE TITLE
Full screen mode and top right menu

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#200]
When Habdroid is setup to work in full screen, when opening the top right menu, the full screen is exited.
##

**Comment by lolodomo** [comment]
This menu has been removed.

**Comment by mueller-ma** [comment]
When you open the about menu, fullscreen mode is exited.

**Comment by lolodomo** [comment]
Dame for settingd. A new issue should be opened.

**Comment by mueller-ma** [comment]
Ok
