### ISSUE TITLE
Demo mode should use OH2 server

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab.android#201]
We are currently running demo servers for OH1 and OH2, where both regularly crash. In order to have less downtime and reduce the efforts required to ensure availability, we should get rid off the OH1 demo server and thus change the native apps to refer to OH2 on http://demo.openhab.org:9080/.

**Comment by belovictor** [comment]
Ok, but would be nice to leave one sitemap on OH2 demo then, cause one of them doesn't look really nice :-)

**Comment by kaikreuzer** [comment]
This was a request from @teichsta - yes, the demo server obviously needs usable sitemaps.
As the fix for this issue is merely changing the server port: @teichsta, if we anyhow have only one instance in future, can't we simply leave it on 8080 and you merely remove the OH1 instance and run the OH2 one on 8080?

**Comment by teichsta** [comment]
sure, we could do that as well 

- sent from a mobile device -

**Comment by belovictor** [comment]
So should I revert both apps back to 8080 then?
@teichsta , when will you move OH2 demo to 8080?

**Comment by teichsta** [comment]
OH2 is running under 8080 now … also changed openhab.org to point to OH2 instance on 8080
