### ISSUE TITLE
How to run sitemap in demo mode in your openhab android application?

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab.android#202]
Hello,
I am trying to do give customization option to customer.This kind task is done in your application.But the thing is how to access the sitemap, when user clicking the profile button.How to save the sitemaps under the user profiles.In your application source code where the sitemaps stored.How to stored the item switch compact states like ON/OFF into database in your openhab android application.
Thanks & Regards
Amar.

**Comment by digitaldan** [comment]
@amarpulli544 , you have opened several issues about the same thing, I think I have been clear that this is something you would have to write, there is no such functionality in the client.
