### ISSUE TITLE
 Saving SwitchCompact state into sqlite database  in openhab android application.

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab.android#211]
Hello,
I am trying to do save switch compact button state like ON or OFF states.In openhab android application when person click the switch compact button, the state is ON at that moment state save into sqlite database in android.how to do this?
Thanks & Regards,
Amar.

**Comment by digitaldan** [comment]
We don't have a local database, so this is more of a general programming question, opening tickets is not a good place to ask these types questions, I would suggest the community forums or stackoverflow.com
