### ISSUE TITLE
Newbie issue- how to make HABdroid work

### ISSUE THREAD

**Issue by tokeiakos** [openhab/openhab.android#214]
HI,
I made a little project using openHAB (simple microcontroller communicating via VCOM with some Rules using the data). I would like to use it on my android telephone, I downloaded the app, unchecked the demo mode, in openhab URL I"ve written http://<openhab address or hostname>:8080, but it cannot find my sitemap. What additional changes should be made in order to make it work?

**Comment by digitaldan** [comment]
you need to put a complete Url in, so if your openhab instance is running on ip 192.168.1.100 the URL you would enter would be
`http://192.168.1.100:8080`

**Comment by digitaldan** [comment]
@tokeiakos if this worked could you comment and close this issue?  Thanks!

**Comment by tokeiakos** [comment]
Thanks for your help, the problem was about the settings of the computer. The application worked  perfectly at home with my computer.
