### ISSUE TITLE
HabDroid not avalaible for Tablet - Excite Go 

### ISSUE THREAD

**Issue by Ronny-GitHub** [openhab/openhab.android#22]
I just bought the Toshiba Excite Go tablet which has the following specs:

•Android™ 4.4, KitKat (running 4.4.2)
•Intel® Atom® Processor Z3735G (2MB Cache, Up to 1.83GHz)
•1GB RAM 
•8 GB storage (4 GB usable)
•7.0” diagonal WSVGA screen at 1024 x 600 native resolution
•Wi-Fi® Wireless networking (802.11b/g/n) + Bluetooth® v 4.0

http://www.toshiba.com/us/tablets/excite/Go/AT7-C8

I thought this is  a nice & inexpensive display / switch for my (KNX) openHab system.

But when I try to download the habDroid client - the google play store tells me that this application is not compatible with my device :(

Any ideas why this is the case? 
Can this be changed to be downloadable via play store?

**Comment by belovictor** [comment]
Can you try to install developer snapshot from here, please: https://openhab.ci.cloudbees.com/job/HABDroid/lastSuccessfulBuild/artifact/mobile/build/outputs/apk/mobile-debug.apk

**Comment by centralspark** [comment]
@belovictor 
>>Can you try to install developer snapshot from here

I was able to install the .apk onto the tablet (by copying it to a folder on the tablet and clicking it from the file manager) and I have successfully run the app.

**Comment by mkoniari** [comment]
Hi i also had the same problem with a no gps tablet. The dev version install and works ok.

**Comment by belovictor** [comment]
Ok, I assume this issue as fixed then, thanks for your help guys!
