### ISSUE TITLE
Map transform not displayed - weird loading issue

### ISSUE THREAD

**Issue by bonieP** [openhab/openhab.android#220]
I do use the FritzBox TR064 Binding under OH2
It is configured like described here: [https://github.com/openhab/openhab/wiki/FritzBox-TR064-Binding](url)

I've got following Item

```
Contact cFboxMacOnline   "Presence (Wifi) [MAP(presence.map):%d]"   <present>   fritzboxtr064="maconline:11-22-33-44-55-66 }
```

with this presence.map file:

```
1=present
0=not present
```

And this corresponding sitemap entry:
`Text item=cFboxMacOnline       icon="network"`

In the Basic UI and Classic UI they are displayed correct.

But in the android app, as soon as i try to open the subpage (Frame) containing this item a blank page is displayed and the loading icon is glitching forever.

I tracked it down to this statement: "MAP(presence.map):" 
As soon as i remove this transformation from the item definition it is working again with the Android app (but obviously not displaying what i want it to).
##

**Comment by lolodomo** [comment]
This looks like very similar to my issue #193.

**Comment by bonieP** [comment]
Closed because its a duplicate like lolodomo suggested
