### ISSUE TITLE
SItemaps without labels cause NPE and application crash

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab.android#236]
The compare functionality at https://github.com/openhab/openhab.android/blob/e7e7dc83576657cc4ce8b1f943c37d2bb5afb000/mobile/src/main/java/org/openhab/habdroid/util/Util.java#L92 is not checking if the label is null and causing a NPE for some users.

**Comment by digitaldan** [comment]
@Br3nda can you take a look at this one?  I am starting to get crash reports since pushing out the sitemap order change that added this compare logic.  Thanks.

**Comment by digitaldan** [comment]
@Br3nda I did a small patch in my repo but have not tested, if you have one that you have tested I would prefer that ;-)

**Comment by Br3nda** [comment]
I think we need a regression test for this too.

**Comment by Br3nda** [comment]
I've added some basic tests in #240
