### ISSUE TITLE
HTTPS SNI support

### ISSUE THREAD

**Issue by LeeNX** [openhab/openhab.android#238]
Setup a second site on my https server and found that my Android App v4.4 would not connect to my OpenHAB site.  

Still able to access the site via FireFox on my NoteBook.  

Was not able to find any information on SNI support in the Android App. Might be an idea to document lack of HTTPS SNI support, until implemented.  

Also did not get an error or indication of progress in the Android App, which was very frustrating, thing it might have been my SSL Tunnel Terminator, reverse proxy or remote connection was down.
##

**Comment by micw** [comment]
Same issue here. I use Let's Encrypt everywhere an I usually have a unique domain name + cert for every application.

My temporary workaround is to set on my openhab nginx vhost:
  listen 443 default_server ssl;

After looking in some SNI implementations for Android, I found out, that it can be done in the following way:

https://github.com/k9mail/k-9/commit/54f9fd36a77423a55f63fbf9b1bcea055a239768

This method is also used in NetCipher: https://github.com/guardianproject/NetCipher/blob/2.0.0-alpha1/libnetcipher/src/info/guardianproject/netcipher/client/TlsOnlySocketFactory.java#L520

Maybe you should consider to use NetCipher to setup TLS/SSL to ensure to always use the best available TLS mechanisms (see recommendtion http://stackoverflow.com/a/40365234/1471588)

**Comment by Dom1n1c** [comment]
I can confirm this issue. I am not able to connect with OpenHAB on Android 7 / Habdroid App with my LG G5.  I also use a Lets Encrypt certificate.

**Comment by digitaldan** [comment]
Hi all, I just started looking at this.  Unfortunately the app uses https://github.com/loopj/android-async-http for its networking and it seems that SNI support is not available, or at least is very broken.  I will need to see if we can fix it in the upstream library and submit a patch, or if we need to replace it with something else.
