### ISSUE TITLE
Crashes on load since update

### ISSUE THREAD

**Issue by brettyj** [openhab/openhab.android#245]
Hi,

I've been using this app for a year or two with no issues, yet with the new update released a couple of weeks ago, every time I launch the app it now crashes. I've sent in a crash report.

I'm on OpenHAB 1.8 version 1.8.0.3 of the android app.

**Comment by digitaldan** [comment]
Hi this is probably #236 , it's been fixed but I have not pushed out a new build to the play store , apologies, I will make that a priority.  In the mean time if you add a label to your site map it should be ok.

**Comment by brettyj** [comment]
Ah, it was a sitemap I had which didn't actually use. Adding a label fixed it, thanks!
