### ISSUE TITLE
Wrong image used for switch in state "off"

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab.android#260]
I have defined an item as switch. In Basic UI it is display correctly:
![image](https://cloud.githubusercontent.com/assets/616792/21504007/b632c5f0-cc5b-11e6-9396-3c998e1e82b9.png)
The green icon is used if the power is on.

In Habdroid different images are used for "on" and "off" state:
If the switcht is off the correct image is used:
![image](https://cloud.githubusercontent.com/assets/616792/21504025/e33ae99c-cc5b-11e6-8b0c-2f644d6500aa.png)
... but if it is switched off the "old" image (wallswitch.png) is shown:
![image](https://cloud.githubusercontent.com/assets/616792/21504065/2a6b1134-cc5c-11e6-82fb-8e0461477df9.png)

**Comment by mueller-ma** [comment]
Did you try to clear the icon cache?

**Comment by lolodomo** [comment]
To be closed, the switch icon is working.

**Comment by MHerbst** [comment]
Forgot about this issue. Is OK now.
