### ISSUE TITLE
Remote URL (vpn) ... extremely slow and does not display images

### ISSUE THREAD

**Issue by sim0nx** [openhab/openhab.android#261]
Hi,

I am using openhab via VPN. For whatever reason I have to configure a remote URL (though this used to work without before).
It takes awful long to load (which is not due to the connection being slow; verified).

When it finally loads the sitemap, there are no icons displayed.
Toggling switches etc works fine, and is fast, also with the feedback.

In the log file I see entries like:
GET /icon/temperature?state=53.0 HTTP/1.1" 200 25938

Which should indicate that habdroid requests icons and gets them from the server.

I would also like to point out that being connected via WiFi on the local LAN works fine speed-wise and regarding icons.

Versions:
- latest habdroid from the store
- openhab 2b5

So I have two issues here:
1. speed
2. no icons

**Comment by sim0nx** [comment]
Update: the icon issue is most probably because I use svg icons (#256)

**Comment by ShaunCurrier** [comment]
I am also using a VPN (OpenVPN) from my android phone and finding that the non-remote URL is not even tried, despite the IP being available through the VPN.  Other apps have no problem with this.

**Comment by sim0nx** [comment]
I found out what my issue here was.
If icons are available as non-svg, they work.

The connection issue was related to openvpn MTU issues.

**Comment by ShaunCurrier** [comment]
Are we sure this should be closed?  What was the openVPN MTU issue?  All my other applications work fine through the VPN, how do we know it's not an openHAB MTU issue?

**Comment by sim0nx** [comment]
I do have a remote URL configured, though I don't understand the reason for i, after re-configuring my openvpn, the issues was solved for me.
The app works fine now via VPN.
As this was my main issue for opening this bug request I am positive that it's appropriate to close it.

FYI I had tun-mtu and mtu-disc set in my config, which messed tings up. Removing both and letting openvpn figure it out solved the problem.
