### ISSUE TITLE
Setpoint Item not working in App, Works perfectly in Browser

### ISSUE THREAD

**Issue by TootToot168** [openhab/openhab.android#264]
The Setpoint functions works via Web Browser but does not work in both Android & iOS. 
When i press the "+" and "-" in the mobile app, it does not call the http commands but when i press the "Up" and "Down" via Web Browser, it works well.

When the AC is turned on with a default temperature, the Setpoint item will appear so that i can adjust the temperature if required.
Using a IR blaster with HTTP urls to send out IR commands to my AC.

OpenHAB Version: 1.8.3
OS: Debian on Raspberry Pi
Java: 1.8.0_111

Phone: Oneplus 3 Android 7.0 Latest OpenHAB Mobile App installed from Google Play Store
**Sitemap**
sitemap default label="testing"
{
	Frame 
	{
		Switch item=FF_AC
		Setpoint item=FFACSetpoint minValue=23 maxValue=26 step=1 visibility=[FF_AC==ON]
		Switch item=SF_AC
		Setpoint item=SFACSetpoint minValue=23 maxValue=26 step=1 visibility=[SF_AC==ON]
		Switch item=TF_AC
		Setpoint item=TFACSetpoint minValue=23 maxValue=26 step=1 visibility=[TF_AC==ON]
		Switch item=4F_AC
		Setpoint item=4FACSetpoint minValue=23 maxValue=26 step=1 visibility=[4F_AC==ON]
	}
}

**Item**
Switch FF_AC { http=">[ON:GET:http://XXX1] >[OFF:GET:http://XXX5]" }
Number FFACSetpoint "Target Temperature [%.1f °C]" <temperature> (All) { http=">[26:GET:http://XXX1] >[25:GET:http://XXX2] >[24:GET:http://XXX3] >[23:GET:http://XXX4]" }
Switch SF_AC { http=">[ON:GET:http://XXX1] >[OFF:GET:http://XXX5]" }
Number SFACSetpoint "Target Temperature [%.1f °C]" <temperature> (All) { http=">[26:GET:http://XXX1] >[25:GET:http://XXX2] >[24:GET:http://XXX3] >[23:GET:http://XXX4]" }
Switch TF_AC { http=">[ON:GET:http://XXX1] >[OFF:GET:http://XXX5]" }
Number TFACSetpoint "Target Temperature [%.1f °C]" <temperature> (All) { http=">[26:GET:http://XXX1] >[25:GET:http://XXX2] >[24:GET:http://XXX3] >[23:GET:http://XXX4]" }
Switch 4F_AC { http=">[ON:GET:http://XXX1] >[OFF:GET:http://XXX5]" }
Number 4FACSetpoint "Target Temperature [%.1f °C]" <temperature> (All) { http=">[26:GET:http://XXX1] >[25:GET:http://XXX2] >[24:GET:http://XXX3] >[23:GET:http://XXX4]" }

**Comment by manmac1** [comment]
the same with me - hope there will be a solution

**Comment by digitaldan** [comment]
This is an issue with the REST api we are using in OH.  We need to switch to using the event socket endpoint which is what the paperui/basicui/habmin use.  This will require a refactoring of the network code which is why it has not been done yet

**Comment by mueller-ma** [comment]
#442 changed the setpoint item to a number picker. The effect described in this issue shouldn't happen anymore.
