### ISSUE TITLE
Voice recognition integration to Google now

### ISSUE THREAD

**Issue by danchiche** [openhab/openhab.android#265]
Hi
Project is huge, all works fine, voice recognition too.
But I would like to control openhab directly from Google now voice recognition.
With this I can operate rapidly with OK Google, and with my Android wear watch.
It's just some few line to put in code.
Thanks :)

**Comment by digitaldan** [comment]
If it's just some line, are you volunteering to do that?

**Comment by danchiche** [comment]
I read on the internet you just need to declare this application is compatible with Google now voice recognition. You need to recreate a special activity for this, but I think it's already integrated.
Unfortunately I think I don't have time to do it.
If I have the time, I setup the environment development, make it and publish it here.
But you know your application better than me.
I think for you is 15 min and for me some week/month to understand the app.
Keep in touch.
Thanks

**Comment by danchiche** [comment]
Hi
I made a simple AUTOMATE script to bring OK GOOGLE directly to openhab (without the third party of openhab android app, and without configuring openhab voicecommand).
This is the like for automate app on Google Play : https://play.google.com/store/apps/details?id=com.llamalab.automate
Click on COMMUNITY button within the app and search for OPENHAB, and you see my script.
It will be better to integrate OK GOOGLE without AUTOMATE, but for now it work grate.
Bye ;)
