### ISSUE TITLE
Custom notification sound + vibration

### ISSUE THREAD

**Issue by Keelhaul** [openhab/openhab.android#27]
Right now HABdroid plays the default notification sound set in the Android device. My phone has the default sound send to none because some other apps also use the default notification sound and don't give you the choice to disable it. Because of that, notifications tend to go unnoticed. Selecting a custom sound for HABdroid and vibration alerts would be a great help!

**Comment by belovictor** [comment]
Notification ringtone can be selected selected in Settings now, this version will be in the Google Play soon, meanwhile you can use dev snapshot if you want!
