### ISSUE TITLE
Charts not shown when Icon format=SVG

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab.android#286]
Hi,

with openhab2 and habdroid 1.8.0.6, when setting "Icon format" is set to "SVG" charts are not rendered anymore.
When changing the setting backto PNG, charts continue to function.

Best,
Sascha

**Comment by AchilleGR** [comment]
Same thing happens for Images defined in sitemaps. Setting Icon format to PNG works as expected.

**Comment by mueller-ma** [comment]
Possible solutions are:

Server-side:
1. Render charts as png and svg (wont display images)
2. Add the format "prefer-svg" which return a png if no svg is available

Client-side:
1. Always use png for charts and pictures
2. Display png if no svg is available

**Comment by lolodomo** [comment]
Sorry, I don't understand why there would be a link between icon format and chart ?
The default chart provider is providing an image in PNG format. Why not just displaying it as it is provided ?

**Comment by mueller-ma** [comment]
The problem is: the charts are fetched correctly, but a svg parser is invoked to display them and that fails.
