### ISSUE TITLE
Unbundle Memorizing Trust Manager

### ISSUE THREAD

**Issue by Flowdalic** [openhab/openhab.android#29]
Memorizing Trust Manager (MTM) can be used as gradle subproject. There is no need to bundle it, and it's in fact counter-productive given that MTM is a critical part of habdroid's security.

I've started an branch https://github.com/Flowdalic/openhab.android/tree/mtm but as I'm not able to get it building with Android Studio (I do my Android development with Eclipse) the branch currently does not compile.

Would be great if someone from the habdroid developers could take a look.

**Comment by belovictor** [comment]
So what is this issue about at the end of the day? :-) I don't think that moving MTM into a separate project would make anything better.

**Comment by Flowdalic** [comment]
> I don't think that moving MTM into a separate project would make anything better.

I think it would (given you mean also that it would become a git submodule). For multiple reasons:
- It makes it easier to determine the currently used version of MTM
- You can easily update/replace MTM by changing the commit the git submodule points to

Older MTM version have some issues, and I can't determine (without comparing the source), if the one used by habdroid is affected.

**Comment by belovictor** [comment]
Unless MTM project provide a usable external dependancy there is no option to separate it. There is some activity in the MTM project to publish the library. As soon as they do it, I will switch to this dependancy and remove MTM code from openHAB app.

**Comment by Flowdalic** [comment]
> Unless MTM project provide a usable external dependancy there is no option to separate it.

You can already use MTM by simply adding it as git submodule. Neither I or Ge0rg (as far as I know) plan to publish it as artifact to e.g. maven central.
