### ISSUE TITLE
Display of selection elements

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#290]
When the current value is not one of the mappings, the displayed value should be an empty string.

Addtionally, valuecolor tag should be handled.

**Comment by mueller-ma** [comment]
@lolodomo Which version of openHAB are you running?
I tested with oh2 and if no mapping for a value is specified nothing is displayed, both in the App and Basic UI.
Valuecolor tags are also working.

**Comment by mueller-ma** [comment]
@lolodomo I didnd see the "selection". Is it possible in Basic UI to use valuecolor and transformation in select elements?

**Comment by lolodomo** [comment]
I am talking about selection element in sitemap with a mapping.
In HABdroid, when you open the selection, you have the mapped values but the selected value when the selection is closed is the non mapped value.
In basic UI, I recently fixed these 2 problems (display of mapped value + handling of valuecolor).

**Comment by lolodomo** [comment]
Look at #https://github.com/eclipse/smarthome/pull/3381 and https://github.com/eclipse/smarthome/pull/3368

**Comment by mueller-ma** [comment]
Item:
````
Number foo2
````

Sitemap:
````
sitemap test2 label="Test"
{
    Frame label="Indoor Climate Control" {
        Selection item=foo2 icon="climate" mappings=[0="Off",1="Heat",2="Cool",3="Auto"]
    }
}
````
HabDroid:
<img src="https://cloud.githubusercontent.com/assets/22525368/26069168/48267252-39a0-11e7-8478-c6f87dee66bb.png" width=500>
<img src="https://cloud.githubusercontent.com/assets/22525368/26069182/4a30e37a-39a0-11e7-81a8-3fcc04c33fbc.png" width=500>

**Comment by lolodomo** [comment]
I suppressed my second message which was totally wrong !
You have to read again my initial issue description. What is not working is when the current value is not a value present in the mappings.
If I take your example, be sure that your item value is 2 (cool) and suppress from the mappings the value "2". You will see that the selection displays a value, probably the first in the list, so probably "Off" in your case.The expected behavior is to have no value displayed.

**Comment by mueller-ma** [comment]
Now I got it. What about the color issue?

**Comment by lolodomo** [comment]
Color is not working too. Try for example to update your sitemap like this:
```
Selection item=foo2 icon="climate" mappings=[0="Off",1="Heat",2="Cool",3="Auto"] valuecolor=[==2="red"]
```
We will see that the text "Cool" remains in black rather than red, when foo2 item value is 2.

**Comment by boc-tothefuture** [comment]
👍 
This issue is also impacting me.  This makes it difficult to use selections and can cause some erratic and unexpected behavior when items are in states that don't match the sitemaps (turning lights on, turning things off, etc).

**Comment by lolodomo** [comment]
The problem is that the android spinner requires a selection.
We could add a blank entry and select it if no mapping is found.
WDYT ?

**Comment by mueller-ma** [comment]
I dont think its a good idea. It would confuse people, when there is a blank entry that doesnt do anything.

**Comment by lolodomo** [comment]
And what about a first entry "Please select..." that will be selected in case of no matching ?
What would be your proposal ?

**Comment by boc-tothefuture** [comment]
Let me know if I should open up a separate issue for this.... However, while the selection is being fixed can we also right justify all selections?  Otherwise things don't line up right in android.  See this screenshot.

![screenshot_20171021-082731](https://user-images.githubusercontent.com/13153815/31851753-11f2e35c-b63a-11e7-9f48-ea3a91b80866.png)


I can open another issue if that is preferred.

**Comment by lolodomo** [comment]
Now that the issue #327 is fixed, it seems more urgent to fix this issue as now there is no more a double information that can help him to understand that the selected item list is wrong.
Can we try to converge to a technical solution ?

**Comment by lolodomo** [comment]
I just proposed something, that is not perfect but largely better than displaying a wrong value.

**Comment by boc-tothefuture** [comment]
@lolodomo  - Its not 100% clear to me from the code.. But is that just adding a 'blank' value essentially?

**Comment by lolodomo** [comment]
In case the current value is not in the list, it displays in the main page a blank value for the selection (like in Basic UI). In this case, if you open the dialog to select a value, you can see a last blank entry.

**Comment by boc-tothefuture** [comment]
Ok - so the downside of the approach is that a blank entry is available when you open it up?  (Just trying to understand your statement of 'not perfect' up above).

**Comment by lolodomo** [comment]
Yes, that is what I consider not 100% perfect. But it only appears when there is no matching.

**Comment by boc-tothefuture** [comment]
Seems to me to be a workable solution.  (not that I get a vote) :-)

:+1:
