### ISSUE TITLE
Default values in settings are "?"

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#295]
After #281 
![screenshot_2017-05-18-15-08-13](https://cloud.githubusercontent.com/assets/22525368/26203510/d915d16c-3bdb-11e7-9df0-d6bc37908920.png)

**Comment by mueller-ma** [comment]
I started fixing it here (https://github.com/mueller-ma/openhab.android/tree/patch-6), but Android Studio gives me following error:
````
Installation failed with message Failed to finalize session : INSTALL_FAILED_TEST_ONLY: installPackageLI.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?
````

**Comment by digitaldan** [comment]
BTW, thanks for fixing this, I don't remember having this issue before and only noticed it over the last week or so as I have been testing.  It's very annoying :-) 

> INSTALL_FAILED_TEST_ONLY
Yes this is super annoying as well, I had to disable "instant run" in the preference menu, also I needed to add "-t" to the install flags under the run configuration (Run menu -> Edit Configurations)

**Comment by mueller-ma** [comment]
Can we use an older gradle version? A non alpha
