### ISSUE TITLE
Make the option configurable to use your own openhabcloud Server

### ISSUE THREAD

**Issue by kobelka** [openhab/openhab.android#301]
When you use your own openhab-cloudserver you have to compile your own openhab app.

Please make it configurable that no user has to compile his own version, see:

#https://github.com/openhab/openhab-cloud/issues/67#issuecomment-293960208

You have to change the  lines 145 and 1201 in OpenHABMainActivity.java to match your system, so please make this configurable in the settings of the openhab App.

Regards
Kobelka

**Comment by FlorianSW** [comment]
Already solved by https://github.com/openhab/openhab.android/commit/4ae13d59da2a402c34d50899ca8b25ca6bff85f5 / PR #288

**Comment by digitaldan** [comment]
Now in store

**Comment by mueller-ma** [comment]
How long does it usually take until everyone gets the update through play store?

**Comment by digitaldan** [comment]
24 hours is usually the max time , most users see it within a hour.

**Comment by mueller-ma** [comment]
I didn't get the update until now
