### ISSUE TITLE
Main title does not change when entering main menu in landscape mode

### ISSUE THREAD

**Issue by TimmyFresh** [openhab/openhab.android#31]
Opearting the openHab app in landscape mode on a 7'' tablet the title is not changed when leaving a group - e.g. when leaving ground floor.
![screenshot_2014-11-15-15-40-47 1](https://cloud.githubusercontent.com/assets/9554467/5058028/11cb013c-6cde-11e4-86f7-616c8b6e819d.png)

**Comment by belovictor** [comment]
Interesting. I can't reproduce it. Which version of Android do you have on your tablet? And is it possible to record a video, showing how it happens?

**Comment by TimmyFresh** [comment]
Hi using 4.3 on my tablet – was about to fix it myself spotted the reason already but had to fight with the project structure. Bye Tom

**Comment by belovictor** [comment]
Can you then tell me the reason to fix it?
