### ISSUE TITLE
Can not connect to local OH using self signed certificate

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab.android#310]
With recent http upgrade we can no longer connect to a local OH instance running a self signed certificate, despite what options are selected in the settings.

@rusitschka can you take a look?

**Comment by FlorianSW** [comment]
This setting isn't observed anymore. I'll take a look and will propose a PR :)

**Comment by rusitschka** [comment]
@FlorianSW that was fast - thanks! :-)
