### ISSUE TITLE
Nested frames do not work

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#324]
In the play store two people are complaining about nested frames are not working (frame in frame).

I could reproduce that.

**Comment by mueller-ma** [comment]
When using nested frames I get following errror message in the oh server log file, so this is intended not to work.
> 2017-10-13 11:55:15.305 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'test.sitemap', using it anyway:
> Frames must not contain other frames

**Comment by mueller-ma** [comment]
>  Frames must not contain other frames

Nested frames aren't supported by the framework. They work in basic ui "by accident".

**Comment by GeorgeEsper** [comment]
Noted. Thank you for responding so promptly.
