### ISSUE TITLE
Habdroid always appends item state in label

### ISSUE THREAD

**Issue by boc-tothefuture** [openhab/openhab.android#327]
Opening an issue based on the discussion [here](https://community.openhab.org/t/remove-item-state-from-a-label/31115/5).

It appears that habdroid does not respect the item or sitemap label and will always append item state.  If you put a [] in your sitemap or item label, habdroid will no longer append the state but you end up with [] in your label text.

Example:

Items:
`Number Thermostats_Downstairs_System_Mode "System Mode" { channel="omnilink:thermostat:home:downstairs:system_mode" }
`
Sitemap:
`Selection item=Thermostats_Downstairs_System_Mode mappings=[0="Off",1="Heat",2="Cool",3="Auto",4="Emergency Heat"]`

This should just render a label that says "System Mode", but habdroid appends the state:
![image](https://user-images.githubusercontent.com/13153815/27940414-7327f8ce-6298-11e7-8c20-a7e9b82f2642.png)

**Comment by mueller-ma** [comment]
I'm trying to reproduce. Which oh and oh app version do you have? Mine is 2.1

Items: 
````
Number foo2 "some label"
````

Sitemap:
````
sitemap test2 label="Test"
{
    Frame label="Indoor Climate Control" {
        Selection item=foo2 icon="climate" mappings=[0="Off",1="Heat",3="Auto"]
        Text item=foo2
    }
}
````

openHAB App:
![screenshot_20170707-182135](https://user-images.githubusercontent.com/22525368/27966911-4e16c192-6341-11e7-9cb1-9bc1659f5e8a.png)

BasicUI:
![oh](https://user-images.githubusercontent.com/22525368/27966963-7b7cbff6-6341-11e7-8f8d-136c4b1a2bf7.JPG)

**Comment by boc-tothefuture** [comment]
@mueller-ma  Thanks for taking a look at this.

I am on OH 2.0 and HABDroid version 1.8.06.


I think you *might* not be able to reproduce it by using a virtual item.

Looking at my image again, specifically the Fan Mode with a degree symbol, I am lead to believe that the HABDroid is pulling the formatting from  appears the channel definition itself.  I was able to validate this by fixing the channel.xml to remove the degree symbol for fan mode.  When I do that, the degree symbol is no longer in the label.

Here is the channel definition:
```
	<channel-type id="thermostat_fan_mode">
		<item-type>Number</item-type>
		<label>Fan Mode</label>
		<description>Fan Mode</description>
		<category>Temperature</category>
		<state pattern="%d">
			<options>
				<option value="0">Auto</option>
				<option value="1">On</option>
				<option value="2">Cycle</option>
			</options>
		</state>
	</channel-type>
```

  I  Although I don't know enough about Habdroid to speculate where it would get that info, but it appears that it is pulling in the state pattern as part of its label if no [] is specified in the label text on either the item or the sitemap?

**Comment by lolodomo** [comment]
In your example with the channel "omnilink:thermostat:home:downstairs:system_mode" where you set no pattern in the item label and no label in the sitemap, the result you got could be the expected result in case a pattern is set for this channel in the binding.

BUT in all cases, if you append `[]` in your item label or add one label ending by `[]` in your sitemap, the value should normally not be displayed.

**Comment by lolodomo** [comment]
Take a llok how it looks like in Basic UI as a comparison.

**Comment by boc-tothefuture** [comment]
@lolodomo Thanks for the response.
Not 100% sure I am following you.  But I think you are saying you need to append [] in one of the labels to make the pattern not be rendered.  

Here is a sitemap with two different options for the system_mode:
```
 Text label="Thermostats" icon="temperature" {
	Frame label="1st Floor" icon="groundfloor" {
		Text item=Thermostats_Downstairs_Temp icon="temperature"
		Text item=Thermostats_Downstairs_Humidity icon="humidity"
		Text item=Thermostats_Downstairs_Status label="Activity [MAP(omniThermostatStatus.map):%s]"
		Setpoint item=Thermostats_Downstairs_Cool_Set icon="temperature_cold"
		Setpoint item=Thermostats_Downstairs_Heat_Set icon="temperature_hot"
		Selection item=Thermostats_Downstairs_System_Mode label="System Mode" mappings=[0="Off",1="Heat",2="Cool",3="Auto",4="Emergency Heat"]
		Selection item=Thermostats_Downstairs_Fan_Mode mappings=[0="Auto",1="On",2="Cycle"] icon="fan"
		Selection item=Thermostats_Downstairs_Hold_Mode mappings=[0="Off",1="Hold",2="Vacation Hold"]
	}
	Frame label="2nd Floor" icon="firstfloor" {
		Text item=Thermostats_Upstairs_Temp icon="temperature"
		Text item=Thermostats_Upstairs_Humidity icon="humidity"
		Text item=Thermostats_Upstairs_Status label="Activity [MAP(omniThermostatStatus.map):%s]"
		Setpoint item=Thermostats_Upstairs_Cool_Set icon="temperature_cold"
		Setpoint item=Thermostats_Upstairs_Heat_Set icon="temperature_hot"
		Selection item=Thermostats_Upstairs_System_Mode label="System Mode[]" mappings=[0="Off",1="Heat",2="Cool",3="Auto",4="Emergency Heat"]
		Selection item=Thermostats_Upstairs_Fan_Mode mappings=[0="Auto",1="On",2="Cycle"] icon="fan"
		Selection item=Thermostats_Upstairs_Hold_Mode mappings=[0="Off",1="Hold",2="Vacation Hold"]
	}
   }
```
Here is what Habdroid looks like:  Note the pattern appended in the first one (even with a label) and then in the second it renders [] instead.
![screenshot_20170707-162536](https://user-images.githubusercontent.com/13153815/27975634-17f1312a-6331-11e7-95ab-f2400f928979.png)


For comparison, here is what I see in basic UI (both cases being rendered correctly, IMO):
![image](https://user-images.githubusercontent.com/13153815/27975685-424c5d14-6331-11e7-91e7-42dccd5abd3c.png)

**Comment by lolodomo** [comment]
I agree with you for the label in second floor that should not show []
For the label in first floor, considering the result in Basic UI, I agree with you too but I would like to see how is defined the binding channel to be sure. I don't find any omnilink binding in OH2 repo.

**Comment by boc-tothefuture** [comment]
@lolodomo thanks for looking.

We are still working on finalizing the binding before we make a PR to get it into the OH2 repo.  For now, it lives here:  https://github.com/QuailAutomation/openhab2-addons/tree/digitaldan-omnilink-binding-thing-types

**Comment by lolodomo** [comment]
Ok so a pattern is defined for this channel and now I understand why HABdroid displays [3] in the first floor By the way, I agree with you that HABdroid should avoid that display in case of a selection element.

**Comment by lolodomo** [comment]
I will fix this issue.

**Comment by lolodomo** [comment]
Fix is now in the review process.
