### ISSUE TITLE
SSL Client Certificate authentication doesn't work anymore

### ISSUE THREAD

**Issue by tulamidan** [openhab/openhab.android#328]
Apparently since the latest update (6.jul) the client certificate authentication does not work anymore on my setup.
I use a self signed CA with a self signed server certificate and user certificates. The whole setup was working smoothly for ~a year.
Then my phone died and I had to setup a new one. Since then my authentication fails. Either "bad request" when I ignore Certificate validation during handshake - or "SSL handshake failed you need a valid user certificate"
I believe my setup is all right as my Browser is able to connect .

**Comment by mueller-ma** [comment]
There has been changes in the http module #275

**Comment by slawekjaranowski** [comment]
I will fix this issue.
