### ISSUE TITLE
Rendering issue with "mappings=[...]"

### ISSUE THREAD

**Issue by Adminius** [openhab/openhab.android#359]
Hello,

i have some issues on Android app. Browser view is better, but also not perfect:
App:
![screenshot_20170905-092155](https://user-images.githubusercontent.com/17052262/30049858-7a648e64-921c-11e7-8d8e-8943d1f63c3f.png)
Browser:
![screenshot_20170905-092130](https://user-images.githubusercontent.com/17052262/30049864-8269ff9a-921c-11e7-99da-1064d2d92909.png)

Landscape mode is ok:
App:
![screenshot_20170905-092211](https://user-images.githubusercontent.com/17052262/30049886-8eb07b8a-921c-11e7-9ac4-88b41d3cfbca.png)
Browser:
![screenshot_20170905-092114](https://user-images.githubusercontent.com/17052262/30049893-95de788a-921c-11e7-8825-206a640138bf.png)

It well be better to have the same "..."  behavior in the app as in a browser .

**Comment by mueller-ma** [comment]
Duplicate of #121

**Comment by Adminius** [comment]
since 2015 not solved :/

**Comment by mueller-ma** [comment]
No one is preventing you from fixing it ;)

**Comment by mueller-ma** [comment]
I'm trying to fix it

**Comment by mueller-ma** [comment]
@Adminius Since this is a duplicate can you close it?

**Comment by Adminius** [comment]
Ok

**Comment by mueller-ma** [comment]
Can you test my proposed fix in #360
