### ISSUE TITLE
Greek language support

### ISSUE THREAD

**Issue by karafyllidis** [openhab/openhab.android#362]
At the moment there is no Greek language support. As a native Greek speaker I would be happy to do the translation needed.

**Comment by mueller-ma** [comment]
What do you mean with "no Greek language support". Does it need more than just the translation?

To translate the app, click on the top right hand corner on fork, create openhab.android/mobile/src/main/res/ values-el/strings.xml and copy https://github.com/openhab/openhab.android/blob/master/mobile/src/main/res/values/strings.xml into the new file. Remove all line containing translatable="false" and than translate the string itself, e.g. "Main menu" in <string name="main_menu">Main menu</string>.
Save the file and make a PR

**Comment by karafyllidis** [comment]
No I am talking about the translation only.

I will start the translation and make a PR when it is ready. Thanks.

Στις 7 Σεπ 2017 6:25 μ.μ., ο χρήστης "mueller-ma" <notifications@github.com>
έγραψε:

What do you mean with "no Greek language support". Does it need more than
just the translation?

To translate the app, click on the top right hand corner on fork, create
openhab.android/mobile/src/main/res/ values-el/strings.xml and copy
https://github.com/openhab/openhab.android/blob/master/
mobile/src/main/res/values/strings.xml into the new file. Remove all line
containing translatable="false" and than translate the string itself, e.g.
"Main menu" in Main menu.
Save the file and make a PR

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openhab/openhab.android/issues/362#issuecomment-327834325>,
or mute the thread
