### ISSUE TITLE
Launcher icon are a bit too small

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#366]
In comparision to other launcher icons the openhab icon seems to be too small.
I generated the icons with https://github.com/romannurik/AndroidAssetStudio. Since this not a bug, it's a feature (https://github.com/romannurik/AndroidAssetStudio/issues/73) it wont get fixed there. I set up a local copy of this generator and wait for the new openhab logo (https://community.openhab.org/t/openhab-logo-update/31242/48). I will submit a PR with the updated logo and resized icon.

**Comment by digitaldan** [comment]
@mueller-ma would you like me to wait for new icons or merge this?

**Comment by mueller-ma** [comment]
Merge this
