### ISSUE TITLE
Scrollbar in dropdown jumps back to top when another item receives an update

### ISSUE THREAD

**Issue by mspoorendonk** [openhab/openhab.android#395]
I have a color picker item and a dropdown item on the same sitemap Frame. The dropdown has about 20 items causing a scrollbar to appear in the dropdown. The colorpicker item receives frequent updates (every 2 seconds due to color sequencing). At every update of the colorpicker the scrollbar of the dropdown jumps back to the top, making it impossible to select the lasts items of the dropdown.

The scrollbar position should be preserved or the dropdown should not be redrawn at all when another item on that Frame receives an update.

**Comment by mueller-ma** [comment]
The dropdown will be replaced by a pop up dialog in the next version.

**Comment by mueller-ma** [comment]
I have opened a selection item, scrolled to the bottom and changed the state of a switch item that is on the same sitemap via basic ui. The switch item gets updated, but the selection popup doesn't jump back to the top. You can see a screenshot of the popup in #393

**Comment by mueller-ma** [comment]
Can you try it with the latest version from play store?

**Comment by mueller-ma** [comment]
Tested it and now the popup doesnt reset or close when the sitemap is refreshed.
