### ISSUE TITLE
Bad Chart URL request crashing app

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab.android#396]
We are seeing an increase in crashes do to a malformed URL, which looks like it's trying to load up the end of a chart URL.  Just in the last Month we have had more than 1000 crashes, all look identical.  This would be easy to catch and protect against a crash, but I also wonder why we have so many broken chart URL requests, sounds like there's an issue somewhere else?  @mueller-ma , @FlorianSW  do you have any ideas about the root cause? 
```

  | 0 | java.lang.IllegalArgumentException: unexpected url: &w=1080&h=540
-- | -- | --
  | 1 | at okhttp3.Request$Builder.url(Request.java:142)
  | 2 | at org.openhab.habdroid.util.MyAsyncHttpClient.method(MyAsyncHttpClient.java:36)
  | 3 | at org.openhab.habdroid.util.MyAsyncHttpClient.method(MyAsyncHttpClient.java:27)
  | 4 | at org.openhab.habdroid.util.MyHttpClient.get(MyHttpClient.java:131)
  | 5 | at org.openhab.habdroid.util.MyWebImage.getBitmapFromUrl(MyWebImage.java:93)
  | 6 | at org.openhab.habdroid.util.MyWebImage.getBitmap(MyWebImage.java:73)
  | 7 | at com.loopj.android.image.SmartImageTask.run(Unknown Source)
  | 8 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  | 9 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  | 10 | at java.lang.Thread.run(Thread.java:761)

```

**Comment by digitaldan** [comment]
@kaikreuzer this is the increase in the number of crashes we discussed.

**Comment by mueller-ma** [comment]
Are different Android version involved?

**Comment by mueller-ma** [comment]
https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java#L494

If chartItem is null here, than it crashed.

**Comment by digitaldan** [comment]
Its happening to all version of android.  @mueller it does look like chartURI was empty here https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java#L529  and so we have a bad URL.  This should not be to tough to fix, if the chart item is null, we should not be trying to retrieve a chart!
