### ISSUE TITLE
Video element: add support for HTTP Live Streaming playlist

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#402]
Please add support for HTTP Live Streaming playlist.
As it is working in Chrome on Android, I suppose it could work in the app too.
You can see how it was easy to update Basic UI and Classic UI: https://github.com/eclipse/smarthome/pull/4386
The general idea is to bypass the proxying and to use a particular media type.

**Comment by mueller-ma** [comment]
This line adds the URL to the player: https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java#L554

It adds http://openhab/proxy?sitemap=test.sitemap&widgetId=0100 which returns (in FF)
`Invalid URL
The requested URL "[no URL]", is invalid.`

But when I hardcode on of the URLs you mentioned [here](https://github.com/eclipse/smarthome/pull/4386#issuecomment-334995466) than it works.

**Comment by lolodomo** [comment]
Very exciting to know that it can work.
Remains to analyze how is built the object openHABWidget by the Android app and to patch it.
Sorry I really don't know the app source code and can't help immediately.

**Comment by mueller-ma** [comment]
It just opens the URL it gets from the rest api

**Comment by lolodomo** [comment]
The sitemap REST API ?
In this case, I could probably have a look myself. More and more exciting lol

**Comment by lolodomo** [comment]
This would be code here:  https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java#L478

**Comment by mueller-ma** [comment]
How does the basic ui access videos? Directly or through oh proxy?

**Comment by lolodomo** [comment]
Basic UI is using the proxy except when encoding is set to HLS.
I think there is 2 changes to apply:
* in the REST API, set url to the default URL defined in the sitemap **but only when encoding is set to HLS**.
* in openHAB app, consider the special case with encoding set to HLS: in this case, use value from item if defined or the value from url if not

On my side, I can change the REST API.

**Comment by mueller-ma** [comment]
When we can get the configured url from the rest api, I can change the android app.

**Comment by lolodomo** [comment]
I submitted the PR for the REST API change: https://github.com/eclipse/smarthome/pull/4412
With this change, the example with `Video url="https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8" encoding="HLS"` is now working in current openHAB app.
As previously explained, a change is still required to consider the case the URL is provided through an item like `Video item="xxx" url="yyy"`

**Comment by mueller-ma** [comment]
Does oh 2.1 support item in a video element? I'm getting the following error:

Items:
`String test_video "Video" <mediacontrol>`

Sitemap:
`Video item=test_video`

Error:
`[WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'test.sitemap' has errors, therefore ignoring it: [42,5]: rule ruleVideo failed predicate: {getUnorderedGroupHelper().canLeave(grammarAccess.getVideoAccess().getUnorderedGroup_1())}?`

**Comment by lolodomo** [comment]
The url= is mandatory in the video element and must contain a default url in case the item is not set.

**Comment by lolodomo** [comment]
For information, if I try `Video url="http://www.openhab.org/assets/smarthome.mp4"`, the video is not rendered in app. In this case, the URL uses the proxy.
Note that it is working in Basic UI.
Could it be due to incompatibility of the Android media player with MP4 files ?
I have not tried to disable the proxy to check if it helps but I will do.

**Comment by lolodomo** [comment]
If I disable the proxying, the video is rendered. It looks like the proxying generates problems with the openHAB app. I don't really know why it is done lkie that (proxy) and if it makes sense for video.

**Comment by lolodomo** [comment]
@kaikreuzer : can you please remind us why we are proxying all images and videos ? It seems to be the source of problems...

**Comment by lolodomo** [comment]
@mueller-ma  :  I have now an Android dev env, I can work on this one if you like.

**Comment by mueller-ma** [comment]
Sure, if you want.

**Comment by lolodomo** [comment]
@mueller-ma : I have a first and stupid problem. My Android emulator is running openHAB app but is unable to connect to any openHAB server on my local network. I just read that the emulator is in fact hidden behind a firewall. Can you please explain what I have to do to connect to any local openHAB server, like the server I am running from Eclipse ?

**Comment by mueller-ma** [comment]
I have the same problem, but mostly I use my physical tablet to run apps.

**Comment by lolodomo** [comment]
@digitaldan :  what's your solution ?

If I use my tablet, the dev app will be installed on my tablet and replace the app installed from the Hoogle store?

**Comment by mueller-ma** [comment]
Yes

**Comment by lolodomo** [comment]
REST API change is now merged.

**Comment by lolodomo** [comment]
Would it be possible to get short explanations on how the app is handling wiidget updates and where is the entry point in the code for the handling of these update events ? Is SSE used ?

**Comment by mueller-ma** [comment]
I don't know it either, but you could start with OpenHABWidgetListFragment line 306

**Comment by lolodomo** [comment]
I want to understand how is worling the app and how the update from server are handled.

**Comment by lolodomo** [comment]
The REST API fix is now available in all OH snapshots.

**Comment by lolodomo** [comment]
Please note I opened issue #417 for the problem with the display of the file smarthome.mp4.
