### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#410]
OH has a new icon: https://community.openhab.org/t/new-logo-for-openhab/35140

I have made some icons for the android app. Since the icon itself it round, we might want to use round icons for all android versions.

1:
![1](https://user-images.githubusercontent.com/22525368/31583530-1b081066-b19e-11e7-8bdb-5cd3c367bd94.png)
2:
![2](https://user-images.githubusercontent.com/22525368/31583531-1b284db8-b19e-11e7-9fef-e5eef9e0e486.png)
3:
![3](https://user-images.githubusercontent.com/22525368/31583532-1b4566be-b19e-11e7-84b6-8d8b6db23b29.png)
4:
![4](https://user-images.githubusercontent.com/22525368/31583533-1b60a0fa-b19e-11e7-931d-ede1c4c6e924.png)
5:
![5](https://user-images.githubusercontent.com/22525368/31583534-1b7d313e-b19e-11e7-9c76-fccf90e6b36a.png)
6:
![6](https://user-images.githubusercontent.com/22525368/31583535-1b98421c-b19e-11e7-8265-bd0e337e2cdb.png)
7:
![10](https://user-images.githubusercontent.com/22525368/31583539-1c3dd98e-b19e-11e7-94f0-54f9fd06642d.png)
8:
![7](https://user-images.githubusercontent.com/22525368/31583536-1bba9d3a-b19e-11e7-85fc-78823292f50f.png)
9:
![8](https://user-images.githubusercontent.com/22525368/31583537-1bdc173a-b19e-11e7-8a49-f4a9f7246216.png)
10:
![9](https://user-images.githubusercontent.com/22525368/31583538-1bf79d70-b19e-11e7-89af-acacf8c0d85b.png)

**Comment by kubawolanin** [comment]
7 looks awesome :-) Long shadows FTW

**Comment by mueller-ma** [comment]
My favorites are 3 and 5

**Comment by kaikreuzer** [comment]
Mine is 3 - I think we should go for a round one as this is hip these days for Android apps :-)

**Comment by digitaldan** [comment]
Nice! lets do 3

**Comment by jmvaz** [comment]
Not a big fan of this new logo… Thinking that this logo will be used on mobile apps, at first sight I cannot recognize what this app really does… this will lead to one usability problem... but is just my opinion...

My vote 3 or 7

**Comment by ThomDietrich** [comment]
I'm surprised by this issue. Wasn't the idea to have one designer provide all needed icons and then stick with those to establish a consistent styling throughout all openHAB parts? If we start to create our own variations now, disaster is inevitable...
For example: The main design consists of a gray circle and the orange triangle. Designs 6 to 10 break with that and the shadow introduced (as nice as it might look) is not part of the original design.

@mueller-ma apart from that I like your designs and would be fine with one of 1-4.

@jmvaz almost every icon is highly abstract and doesn't identify the function of the app. See the facebook f or any other icon on your homescreen. Associated meaning is generated in our minds from memory and you'll very soon get used to it.

**Comment by kaikreuzer** [comment]
@ThomDietrich I agree with you and that's why I voted for 3 as this is what came out from the logo design - the logo on a white circular background. Android and iOS have some specifics on the exact shape, resolution and use of shadows, though, which isn't yet created - this is something I am handing over to @digitaldan as he planned to do new app releases soon.

I think @mueller-ma suggestions are great as it gives an idea about the options. 6-10 is in the style that our current app icon is, so it is fair of him to list those as well. But I think we all agree that we should go back to the "normal" app icon now. So Android should be (3), while iOS uses the shape of (1). @mueller-ma I suggest you leave the update to @digitaldan as he also has access to the appstores and can update all required data there at the same time.

One question to all app experts though: From what I see from other apps, putting a shadow behind the logo is not very common - so shouldn't it rather be completely flat without any shadow?

**Comment by mueller-ma** [comment]
> @mueller-ma I suggest you leave the update to @digitaldan as he also has access to the appstores and can update all required data there at the same time.

It doesn't really matter if @digitaldan or me makes the PR, that changes the icon. It will only be visible to the user, when Dan uploads a new version.

No shaddow at all:
![11](https://user-images.githubusercontent.com/22525368/31628715-dc4f08b0-b2b1-11e7-8162-db6339414962.png)
"Elevate" shaddow:
![12](https://user-images.githubusercontent.com/22525368/31628716-dc6fbd26-b2b1-11e7-91a3-af45b484b4e4.png)

**Comment by kaikreuzer** [comment]
Thanks - we should go for no shadows as this is how we use the logo at all other places as well.

**Comment by mueller-ma** [comment]
Ok, I will update the pr.

**Comment by kabili207** [comment]
Since we're updating the icon, should we also consider supporting the adaptive icons that Google introduced with API 26? https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by mueller-ma** [comment]
Some work need to be done, when we target 26. I heard, that it is possible to compile with 26, but still target 25. Someone with an android 8 device needs to test it.

**Comment by mueller-ma** [comment]
With the dark themes the circle is hardly visible. Maybe we should use the icon with the white background everywhere in the app?

![screenshot_20171019-205958](https://user-images.githubusercontent.com/22525368/31788947-b46d6dd0-b510-11e7-9360-a60b2f9f25e3.png)
