### ISSUE TITLE
Replace Apteligent crash reporting with Crashlytics

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab.android#411]
Googles preferred (and free )crash reporting for android and IOS

https://fabric.io/kits/android/crashlytics/summary?ref=fb

**Comment by mueller-ma** [comment]
Free = no cost != free license?

**Comment by digitaldan** [comment]
Apteligent has switched to a pay only license that is not in our budget, so we need look at other alternatives.   Googles acquisition  of fabric.io, and subsequent changing it to a free service seems very appealing.

**Comment by mueller-ma** [comment]
Can be closed?
