### ISSUE TITLE
Several entries in double in strings.xml for German

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#416]
minus, plus, main_menu, ...

**Comment by mueller-ma** [comment]
In https://github.com/openhab/openhab.android/pull/391/files#diff-5ca5147a9754be194f0298defed14367L111

**Comment by lolodomo** [comment]
Note that I mentioned this error as I got a compilation error when I try to run the application.

**Comment by lolodomo** [comment]
It is apparently fixed after the recent changes in the master branch.
