### ISSUE TITLE
Some small features for a wall mounted tablet

### ISSUE THREAD

**Issue by Furrer** [openhab/openhab.android#42]
For my wall mounted tablets (Android 4.4), which should only be used to control my OpenHab server, I would like to see the following features
- Fullscreen mode (configurable)
- A back button which will not automatically close the app, if I use it accidentally in the main screen. I would prefer to have a configuration option to be asked if I will close the app when using back in the main screen
- A configurable timeout after which the app automatically jumps back to the main screen

For using on my phones it would also be nice to have a possibility to have a line break within the labels.

**Comment by digitaldan** [comment]
I have one and two already done in a pr ( see #21 ), let me see if I can
post this somewhere for u to try out,  I had not thought about the timeout
to the home screen, I like that idea, if I have some time I might play with
that . I have 4 nexus 7's that I have in stands or picture frames around
the house.
Sent from my mobile.

On Jan 1, 2015, at 10:21 PM, Andreas Furrer <notifications@github.com>
wrote:

For Sent from my mobile.

   - Fullscreen mode (configurable)
   - A back button which will not automatically close the app, if I use it
   accidentally in the main screen. I would prefer to have a configuration
   option to be asked if I will close the app when using back in the main
   screen
   - A configurable timeout after which the app automatically jumps back to
   the main screen

For using on my phones it would also be nice to have a possibility to have
a line break within the labels.

—
Reply to this email directly or view it on GitHub
<https://github.com/openhab/openhab.android/issues/42>.

**Comment by Furrer** [comment]
Thanks for the info. Unfortunatelly there is no new build of HabDroid on https://openhab.ci.cloudbees.com/job/HABDroid/ so I tried to build it by my own.
I have installed Android Studio 1.02 and downloaded the latest source, but I failed in building the APK.
I'm an old school windows developer (C,C++,Delphi etc.) and for me developing for Android seems to be very confusing...
Maybe you can send me an APK for testing? This would be great.
Thanks
Andreas
