### ISSUE TITLE
Crash when chart refresh too low

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#420]
I set the refresh to 10, no chart was shown and the app crashed after some time.
Version 1.8.0.8

**Comment by lolodomo** [comment]
You are crazy to use such a small refresh frequency (10 ms) ;)
In Basic UI, we have considered a minimum value of 100 ms.
This should be considered in method https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java#L92
Minimal value should be adjusted after some testing. Maybe 100 ms is even too small.
