### ISSUE TITLE
Selection box: selected item not emphased

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#423]
With the current master branch, selecting a selection opens a sub-window in which you can select your value. There is nothing that shows what is the current selection. I see there is some code for that so I assume there is a bug in the code.

**Comment by mueller-ma** [comment]
I also have thought about this, but I couldn't find a way to tell which value is the current one.

**Comment by lolodomo** [comment]
Was it finally not a good idea to keep the current value between [] in the title ?

**Comment by ThomDietrich** [comment]
The current value is shown in the sitemap, when clicking it the sub-window is shown and a new value can be chosen. Sounds okay to me.
That said it would of course be nice if the current value would additionally be the preselected entry in the selection sub-window.

**Comment by lolodomo** [comment]
Yes, I agree that it is a minor issue.

**Comment by mueller-ma** [comment]
What about radio buttons like in basic ui?

**Comment by lolodomo** [comment]
If possible, yes, good idea.

**Comment by FlorianSW** [comment]
I like the radio button idea, on it! :)

**Comment by FlorianSW** [comment]
This is how the selection looks like when using radio buttons:

![screenshot_20171108-203829](https://user-images.githubusercontent.com/4892966/32570594-d911b8ee-c4c4-11e7-9171-5b726428c074.png)

**Comment by lolodomo** [comment]
That's cool.

**Comment by maniac103** [comment]
Using CheckedTextView with checkmark to the left might look even better though...

**Comment by mueller-ma** [comment]
Wouldnt this suggest that more than one item could be selected?

**Comment by maniac103** [comment]
Don't think so. I'm pretty sure I've seen something like that being used in AOSP, I just can't remember where at the moment :-/
