### ISSUE TITLE
Use Kotlin?

### ISSUE THREAD

**Issue by holmes** [openhab/openhab.android#428]
Hi all,

What are the thoughts on using Kotlin in this app? I've got a few things that I'd like to contribute, and I'm a big fan of Kotlin. Would love to use it on the new features.

Thoughts?

**Comment by mueller-ma** [comment]
Hey @holmes,

I just have read some articles about the advantages of Kotlin and it looks very nice. Adding kotlin support can be done by Android Studio automaticly and adds 4 lines, so thats not the problem. However I don't know how many people can read/write Kotlin and I don't think its a good idea to mix both languages (not from a technical aspect, but from understanding the code).

> Would love to use it on the new features.
About what features are you talking?

**Comment by holmes** [comment]
As to features: the first one I'd like to add is [App Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts.html) for the various sitemaps.

As to Kotlin: I use it professionally in a mixed Java/Kotlin environment and it works great. Kotlin is a great future and I think you'll find a lot of developers would like to work with it. Especially those that don't get a chance to do it in their day jovs.
With the native support that Android Studio has switching between Kotlin & Java is actually pretty easy.

Please re-think green-flagging Kotlin. I think it'd be a great opportunity for the community.

**Comment by mueller-ma** [comment]
> the first one I'd like to add is App Shortcuts for the various sitemaps.

Please have a look at #392. Sitemaps are not ment to be a navigation elemtent.
Also look at #334 for a better usage of shortcuts.

@digitaldan Whats your opinion on Kotlin?

**Comment by boc-tothefuture** [comment]
👍 
I don't get a vote here, but I would be pro mixing kotlin into the code base.  In my experience mixing java with kotlin works well and lets you get a lot of the kotlin benefit.

**Comment by mueller-ma** [comment]
What do you mean with mixed? Some files in java and some kotlin? Or in a file a function in java, other in kotlin?

**Comment by boc-tothefuture** [comment]
I have only ever seen it done on a per file basis. 

Android studio makes it fairly easy to interoperate between the two.

**Comment by mueller-ma** [comment]
Feel free to send a PR with Kotlin :)
