### ISSUE TITLE
Use a number picker for Setpoint, etc.

### ISSUE THREAD

**Issue by sansei4** [openhab/openhab.android#429]
![image](https://user-images.githubusercontent.com/7754105/32126569-a57bc328-bb71-11e7-8f71-3c6c40cb613d.png)

Benefits:
- Native behaviour
- No delay - doesn't need to wait for server reply after each state change (sometimes it takes a very long time until it changes, )
- Sometimes the value is not updated at all, only after a screen refresh - i.e. I have to go to the next/previous page and back, to see the new value. Otherwise each pressure on the "plus" sends the same value.
- Reducing the data bus traffic.
- Elimination of an unexpected behaviour of the end device, through the obtaining an intermediate value.

I suppose, it depends on the core as well, but I don't know, what exactly is needed to implement this feature.

**Comment by mueller-ma** [comment]
No need to add "#429" to the title.

**Comment by sansei4** [comment]
How to set a label?

**Comment by mueller-ma** [comment]
Labels can only be set by people with write access.

**Comment by boc-tothefuture** [comment]
:+1:  On this idea.  Using the setpoint value right now for things like temperature and in some cases volume (I know there is a slider, but I often find I don't get enough control w/ the slider) can often not be the best user experience.  Often the presses are not registered as quickly as I want them to be.

**Comment by mueller-ma** [comment]
I haven't found a way to implement this with the android dialog.

**Comment by boc-tothefuture** [comment]
@mueller-ma  - Does it need to be a dialog?  I was playing with it and even if its not a dialog the user experience seems better than the button presses. (although I haven't wired it up)
