### ISSUE TITLE
Selection Items should be right justified

### ISSUE THREAD

**Issue by boc-tothefuture** [openhab/openhab.android#439]
As per the discussion in #290 I am opening a new issue on the selection items needing to be right justified. 

Presently the items are not right justified and therefore don't line up correct, see picture below:
![image](https://user-images.githubusercontent.com/13153815/32279070-01ddeb9e-beee-11e7-88b9-42c4f8996926.png)

**Comment by mueller-ma** [comment]
What values have the selections?

**Comment by mueller-ma** [comment]
Can you post a screenshot of the apk posted [here](https://github.com/openhab/openhab.android/pull/436#issuecomment-340875448)?

**Comment by boc-tothefuture** [comment]
@mueller-ma  - Here are the selection:
```
Selection item=Thermostats_Downstairs_System_Mode label="System Mode" mappings=[0="Off",1="Heat",2="Cool",3="Auto",4="Emergency Heat"]
		Selection item=Thermostats_Downstairs_Fan_Mode mappings=[0="Auto",1="On",2="Cycle"] icon="fan"
		Selection item=Thermostats_Downstairs_Hold_Mode mappings=[0="Off",1="Hold",2="Vacation Hold"]
```

I am not sure what you mean by post a screenshot of the APK posted here?  You just want me to add that screenshot showing the undesired behavior to the other issue?

**Comment by mueller-ma** [comment]
Would be good if you can install the apk from posted [here](https://github.com/openhab/openhab.android/pull/436#issuecomment-340875448) and test it again.

**Comment by boc-tothefuture** [comment]
Gotcha.  Will do.

**Comment by boc-tothefuture** [comment]
@mueller-ma - Problem persists with the debug apk in the other thread.

**Comment by boc-tothefuture** [comment]
@mueller-ma - I took a pass at resolving this in that PR.
