### ISSUE TITLE
When choosing SVG icons, Image items are not being displayed

### ISSUE THREAD

**Issue by chiefymuc** [openhab/openhab.android#443]
I am using an Image element to display a webcam still every 30 seconds. It is a JPEG.

If in the settings I choose SVG icons, the element is not diplayed. With the PNG setting it works.

**Comment by lolodomo** [comment]
It is already fixed in the master branch.

**Comment by lolodomo** [comment]
Very probably by PR #372

**Comment by mueller-ma** [comment]
I think it should be fixed. But when the "fix" disabled svg in image items. I think I will need to refactor it a little bit.

**Comment by mueller-ma** [comment]
Can you try it with the latest version from play store?

**Comment by mueller-ma** [comment]
Tested it and it works now.
