### ISSUE TITLE
Android Studio - Compilation issue

### ISSUE THREAD

**Issue by jainhemendrah** [openhab/openhab.android#457]
Dear All,
  I am using Android Studio v2.3.3.  (Win 7 - 64 bit)

I  downloaded the Android code and tried to build the same.
I chose "Open an Existing Android Project"
I am getting following errors when compiling:

Error:Android Source Generator: [openhab.android-master] AndroidManifest.xml file not found.

Any help would be appreciated !!!

**Comment by mueller-ma** [comment]
Maybe this helps: https://stackoverflow.com/questions/16908222/androidmanifest-xml-file-not-found/30843009#30843009
Also "File -> Synchronize" or restarting Android Studio helps sometimes.

**Comment by jainhemendrah** [comment]
Will try...

**Comment by jainhemendrah** [comment]
Switched to Linux - issue resolved
