### ISSUE TITLE
Image in sitemap 

### ISSUE THREAD

**Issue by 9H1LO** [openhab/openhab.android#459]
Image in sitemap not always shown and when it does it is slow and doesn't usually refresh

when accessing with chrome on android its fine

Image label="LivingCAM" url="http://172.16.10.106/zm/cgi-bin/nph-zms?mode=single&monitor=2&scale=50&user=xxxx&pass=xxx" refresh=500

**Comment by mueller-ma** [comment]
Maybe the same reason in #420. Can you try 5000 as refresh rate?

**Comment by 9H1LO** [comment]
yes, works fine with 5000 albeit very slow frame rate

**Comment by lolodomo** [comment]
You can experiment smaller refresh rate.
It probably depends on how big is your picture and how available is your device to answer.

**Comment by mueller-ma** [comment]
Currently it reloads the picture after e.g. 5s are over and does not wait for the previous load to finish.
Thats the problem in #420 and I think also here. It makes requests over and over without waiting to finish, reserving more and more space and than crashes due too no free space.

**Comment by lolodomo** [comment]
We should avoid triggering a new refresh while the image loading is still in progress.
I can try to enhance that.

**Comment by mueller-ma** [comment]
Thanks for working on it. Apart from that the image shouldnt be cleared until the new one is loaded.

**Comment by lolodomo** [comment]
Looking at the code of SmartImageView, it looks like each call to setImage is using a task to download and set the image and this task is first cancelled if one is already in progress. So it should normally avoid having in parallel several downloads of the same image but I think it could lead to the thread being always killed before it finished its job and as a consequence the image being never updated.
I will have to debug to understand. The change to apply is not yet clear for me.

**Comment by lolodomo** [comment]
The library offers the ability to set a completeListener. We could use to know if a setImage action is in progress or finished. If one is in progress while the refresh is triggered, we could just ignore this refresh (and wait for the next one).
I can try this solution.
