### ISSUE TITLE
Failed to find Build Tools revision 26.0.2

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#474]
After an update to the last sources, when I open Android Studio, I got this error: Sync with Gradle for project 'openhab-android' failed: Failed to find Build Tools revision 26.0.2

Why tools revision 26.0.2 are now required ?
Until now, I was using only SDK platform 4.0.3 (IceCreamSandwich).

**Comment by mueller-ma** [comment]
In https://github.com/openhab/openhab.android/pull/455 I changed the source of android-smart-image-view from oh maven to jitpack.io. The build failed and when I searched for that error, I found out, that it is fixed with build tool 26.

**Comment by lolodomo** [comment]
Just to be clear, does it mean we have now to all move to SDK platform 8.0 ?
Will the app still work well on old android versions ?

**Comment by mueller-ma** [comment]
It shouldnt change anything with target and min api.

**Comment by lolodomo** [comment]
Ok, thank you for the clarification.

**Comment by wasimshahagadi** [comment]
just download this file and extract it. https://dl.google.com/android/repository/build-tools_r26.0.2-windows.zip copy all files from [android-8.1.0] and move them into C:\Users\user\AppData\Local\Android\Sdk\build-tools\26.0.2

**Comment by cacious7** [comment]
Thanks, your answer @wasimshahagadi  worked for me...

**Comment by jpskonee** [comment]
@wasimshahagadi your answer was really divine.. thanks bro!!!

**Comment by olcaydaser** [comment]
@wasimshahagadi  nice!

**Comment by sgc109** [comment]
@wasimshahagadi I love you

**Comment by kainaspatel** [comment]
your solution is working bro :) 
additionally you need to make sure below thing in app level build.gradle file

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"    // <<<<<<<
        }
    }
}

**Comment by Abror98** [comment]
error
