### ISSUE TITLE
Number picker is not discoverable

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab.android#476]
After merging #442  the + and - buttons are now removed from the spinner widget, which now does not look like it can be selected.  There is no difference now between the number picker value and a non selectable value.  If you look at the official demo.openhab.org site, this is very apparent as under the widget overview we have a label of "Temperature" and then a picker to set the value.  If you drill down to any of the rooms we also have a "Temperature" label, but the value is NOT selectable, but looks identical to the clickable version under the widget overview.

**Comment by mueller-ma** [comment]
Thats also a problem I saw, but I couldnt find a way to make it look clickable. Maybe a button with a pencil next to the value?

**Comment by digitaldan** [comment]
> Maybe a button with a pencil next to the value?

or the down arrow that is used by a selection widget?  Does Google have an official stance on this?

**Comment by mueller-ma** [comment]
@boc-tothefuture

**Comment by boc-tothefuture** [comment]
I am not sure... I did a google image search and didn't come up with anything. 
I am ok w/ a pencil?

**Comment by mueller-ma** [comment]
I couldnt find a solution from google. I think a pencil button could be a bit overkill, @boc-tothefuture can you try the suggestion by @digitaldan. 
Another thing with the number picker: When I tap on the label of any item type nothing happens, but for number items the number picker opens. I think its better when it only opens when tapping on the number.

**Comment by boc-tothefuture** [comment]
@mueller-ma - 
  I found it very difficult to select the number before which is why I expanded the touch space to the entire line. I will revert that and see what happens.   
  Any idea where we can get the down arrow from the selection widget?

**Comment by boc-tothefuture** [comment]
@mueller-ma I pushed #507 to resolve this.  Would you mind taking a look w/ a critical eye towards the layout segments? 

Thanks!
