### ISSUE TITLE
Move "Select default sitemap" to the settings menu

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab.android#479]
In https://github.com/openhab/openhab.android/pull/404#issuecomment-347045797 it seems we've a consensus to kill the options menu and move all the possible buttons into better places around in the app. One of the options is the "select default sitemap", which should clearly be somewhere in the settings.

That's the issue for solving this.

**Comment by FlorianSW** [comment]
I plan to work on this, once #391 is merged :)

**Comment by lolodomo** [comment]
@mueller-ma : you should change the milestone to 2.0.1 as the PR does even not yet exist.

**Comment by mueller-ma** [comment]
Yes, but this is the last point in the menu

**Comment by lolodomo** [comment]
I have NFC stuff too.

**Comment by FlorianSW** [comment]
@lolodomo For NFC, we don't have a plan yet what we do with it, as it serves context-specific tasks (create a nfc tag which will open the app with this specific sitemap page). For the "Select default sitemap" we already know what to do (move to the connection settings in the settings), which is also a pretty easy change. I plan to create a PR today, even if PR #391 isn't finished, yet (shouldn't have bigger conflicts when I think about it). Is that ok for you? :)

**Comment by lolodomo** [comment]
Yes of course ok for me if this can be implemented so quiclly.

For NFC I never understood what is this feature for. Can you explain ? Is it possible to disable it through a user setting ?

**Comment by FlorianSW** [comment]
@lolodomo For the NFC thing I created #515 and explained how I understood the feature from reading the code. Let's discuss there, if we need it :)
