### ISSUE TITLE
German translation: Du vs Sie

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#486]
@kaikreuzer @maniac103 @FlorianSW WDYT?

**Comment by maniac103** [comment]
I strongly prefer 'Sie', but I guess I'm oldschool considering even AOSP is switching to 'Du' ... the closeness implied by 'Du' feels somewhat unprofessional to me.

**Comment by kaikreuzer** [comment]
Ideally you should avoid the question altogether by rephrasing your sentence.

**Comment by maniac103** [comment]
This can sound weird, though. Random example:

`Berühren Sie den NFC-Tag und warten Sie auf die Bestätigungsmitteilung`

Really rephrase as

`NFC-Tag berühren und auf Bestätigungsmeldung warten`

considering it's a hint/help text?

**Comment by kaikreuzer** [comment]
You are right, for longer help texts where you need to guide someone, it sounds weird.

So I'd also clearly vote for "Sie" (probably flagging me old-school as well now ;-)).

**Comment by ThomDietrich** [comment]
+1 for "Sie"

An alternative I often see is that two translations are offered.

Edit: I wanted to see how other systems do it and looked at the Android settings... There I actually found both methods. Whatever you choose, please don't do that :D

**Comment by mueller-ma** [comment]
I also think "Sie" is better.

@ThomDietrich Maybe some strings are from AOSP and some from the vendor.

**Comment by maniac103** [comment]
@ThomDietrich @mueller-ma is spot on here. AOSP historically used 'Sie', while Google apps use 'Du'. In places that integrate the latter into the former (like in the settings app) this looks weird (as you noticed), which is why they move everything to 'Du' now I guess. They should better have chosen the other direction, but oh well.

**Comment by FlorianSW** [comment]
So, I personally like Du, however, as long as we do not mix, Sie is ok, too :)
