### ISSUE TITLE
Provide USAGE.md for docs.openhab.org

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab.android#495]
Hey everyone!

over at docs.openhab.org we realized, that is a good practice, to store articles related to e.g. certain add-ons in their respective repositories. This step makes keeping them up to date easier. A script to sync those files back into docs is in place.

The android app article is currently maintained inside the docs repo: http://docs.openhab.org/addons/uis/apps/android.html / https://github.com/openhab/openhab-docs/blob/gh-pages/addons/uis/apps/android.md

Similar to e.g. https://github.com/openhab/openhab-alexa or https://github.com/openhab/openhab-mycroft I'd suggest to add a file USAGE.md to the openhab.android and openhab.ios repository. Feel free to use the docs articles as a starting point. Please be sure to add the front matter header as can be found in the alexa/USAGE.md file.

It would be great if one of you (@mueller-ma perhaps) could take the lead on this task. I'll do the wok on docs side once you are ready. Thanks!!

Best! Thomas

**Comment by mueller-ma** [comment]
What should I do with screenshots? Include them in this repo or somewhere in openhab-docs?

> Please be sure to add the front matter header as can be found in the alexa/USAGE.md file

I cannot see any special header. What do you mean with that?

**Comment by ThomDietrich** [comment]
Ah, I see, yes those are different.

A better example is maybe: https://github.com/openhab/org.openhab.ui.habpanel/tree/master/doc

There you can see the special header and the idea to add screenshots to the `images` subfolder. You could also put everything into the `doc` folder.

**Comment by mueller-ma** [comment]
Currently we have all screenshots in /fastlane/metadata/android/en-US/phoneScreenshots/. I want to avoid duplicate files, so will symlinks to /docs also work?

**Comment by ThomDietrich** [comment]
I see. Yes symlinks would be fine with me. The important part is, that the Usage articles needs to include images from the images folder: `<img src="images/android_01.png" ...>`

May I ask why screenshots need to be deep down in the folder structure? I'm no android dev, what's fastlane? Could you perhaps put the symlinks there and move the images to the images folder?

**Comment by mueller-ma** [comment]
Fastlane is a tool to make play store releases easier. @digitaldan doesnt use it, but when providing metadata in this structure, F-Droid picks it up and shows it on the app site.
