### ISSUE TITLE
Subscript text not rendered properly

### ISSUE THREAD

**Issue by 8666** [openhab/openhab.android#50]
I have data for the air quality outside: like PM10 concentration, Ozone levels (O3) etc and numbers are displayed fine as subscript in web browser. I am using O&#8323; for Ozone. 

In the Android application it is displayed raw with the HTML code for that character. I do not want to make special sitemap just for mobile where I will not use special codes

**Comment by cribskip** [comment]
So you used 
```
O<sub>3</sub>
```
in your sitemap?

Then the label text must be parsed HTML in the app.

IMHO, parsing HTML in full for every refresh and with every item would be resource intensive. Maybe a set of tags may be acceptable.

**Comment by belovictor** [comment]
Well, the current REST API design of openHAB doesn't have any specifications on label or value usage of HTML tags. Moreover, both iOS and Android apps just show up a string received from openHAB's REST API. So I would assume this should be created as an issue for openHAB itself to include such requirements into value/label formatting. As soon as such feature is implemented and documented into openHAB REST API it will be supported in mobile apps.
