### ISSUE TITLE
Google Cloud Message: not working ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#502]
In the about window, I can see for GCM this message in French 
> Echec de l'enregistrement de l'appareil avec l'ID %s

So, I see two problems:

1. Why %s is not replaced by a real ID ?
2. Why the registering is not working ?

**Comment by maniac103** [comment]
Does the string say registration failed? If yes, it needs to be updated to not include the ID, which was null anyway. See the new code at https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java#L173 ... I thought I had done that update though (?)

**Comment by lolodomo** [comment]
It is the string `info_openhab_gcm_not_connected`.
Ok, I am fixing the french translation immediately.

Why the connection is failing ?

**Comment by lolodomo** [comment]
Is there something special to do to get a working GCM registration ?

**Comment by mueller-ma** [comment]
Have selected a build flavor? There is currently no documentation over them #505

**Comment by maniac103** [comment]
Is this with a self-built APK? In that case GCM won't work as it (AFAIK) only works with APKs that are signed with the key specified upon registration of the GCM API key.

**Comment by lolodomo** [comment]
The registration is working on my phone which uses the official app version from the market.
On my tablet, I am using a version installed from within Android Studio and so I understand that it is normal that GCM registration is failing in that case.

**Comment by mueller-ma** [comment]
I'm not 100% sure, but I think I registered my device with a self built apk

**Comment by mueller-ma** [comment]
@lolodomo Did you change the build flavor?

**Comment by lolodomo** [comment]
No, I even don't know what is "flavor" ;)

**Comment by lolodomo** [comment]
@mueller-ma : without your new explanations in the doc, I will probably never see the "build variants" at left !!! fossDebug was selected. I switched to fullDebug. But GCM registration is still failing after runnign mobile. My tablet is only a wifi tablet, can it be a valid reason ?

**Comment by mueller-ma** [comment]
Should work with wifi only. Do you have a remote url set? And are play services installed on the device? Do you have some kind of firewall on the tablet?

**Comment by lolodomo** [comment]
No I have no remote URL set as I use the tablet only in my local network. Is it the reason ?

**Comment by mueller-ma** [comment]
Yes, GCM is only needed for receiving notifications from openhab cloud.
