### ISSUE TITLE
Decide what to do with NFC "Link to Sitemap page"

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab.android#515]
From what I read from the code, the NFC option at the options menu at the top right has the following functionality:
* Once the user taps this option, the NFC tag write activity is started
* the parameter sitemapPage is passed to that activity, which contains the url of the curretnly displayed sitemap page (I assume e.g. a sub-category or something like that)
* The user could write a NFC tag now, which, when recognized by the system, will open the app and the specific sitemap page

I don't use this feature, so probably I missed something when reading the code, or is this functionaliyt correct?

If so, this is the only menu entry left in the options menu and, to be honest, I really doubt, that someone really uses this feature. What would be the use case? What is the benefit over having an nfc tag, which directly controls an item (like you can create when long-pressing an item in the app)?

With this Issue I would like to ask into the round: Do we really need such a functionality or can we simply kill it?

**Comment by digitaldan** [comment]
I vote to remove.

**Comment by mueller-ma** [comment]
+1 remove

**Comment by maniac103** [comment]
+1 remove

**Comment by kaikreuzer** [comment]
Argh, not getting reliable notifications from Github these days - and one of my favorite features has been removed within 5 days :-(

I clearly vote to keep it.
It is one of the most useful features about NFC support, which I also regularly mention at conference talks and it even has its own YouTube video on the openHAB Channel: https://youtu.be/NgsFGtuUFSw?t=25s

Any chance to get it back again? I have no issues if you want to move the menu item somewhere else (e.g. as a long press on the page title).

**Comment by FlorianSW** [comment]
Hi @kaikreuzer Damn, and I really thought, no-one really uses it (as I doesn't see any use case for it). However, my main point of _removing_ it, was to get rid of the options menu, so if you're ok with having the option in the long press-menu of every item (also groups), I would be happy to re-introduce it there :)

**Comment by FlorianSW** [comment]
I opened #527 for that :)

**Comment by digitaldan** [comment]
Long pressing an item is how nfc tags are associated with items , so I think this has to go the bar menu , or in the bar itself

**Comment by FlorianSW** [comment]
Is there a problem having a separate item "Link to this sitemap page" or something like that?

**Comment by maniac103** [comment]
I've added some placement suggestions to #527.

**Comment by kaikreuzer** [comment]
Thanks for re-opening it, although no one of you thought it is in any way valuable 😇 !

Isn't it possible to put the feature as a long press on the header text, which shows the name of the current page (e.g. "Ground Floor")? This would be the most logical place, as the long press on the widgets underneath is also used for NFC.

**Comment by FlorianSW** [comment]
I'm not sure, if this place for the feature is discoverable at all for the user? The header normally doesn't take any long-press-options (at least I haven't seen any app, which does that).

**Comment by kaikreuzer** [comment]
Up to you, I don't care too much where it is located as you only have to program it once for a page and never again.
