### ISSUE TITLE
Android Wear Voice Integration

### ISSUE THREAD

**Issue by jwc905** [openhab/openhab.android#52]
Habdroid already provides voice commands but it requires either being in the app or selecting a widget.

By declaring an App-provided Voice Action it would be possible to directly send voice commands from an Android Wear device without the need to first open a widget or app.

https://developer.android.com/training/wearables/apps/voice.html

**Comment by dominicdesu** [comment]
I agree, this would be really cool. Do you have experience with this? Would
it be necessary to say "OK google, turn on the light in the living room
with Habdroid" or is there an even easier way?

**Comment by jwc905** [comment]
At a minimum one could do 'ok, google start openhab' then the activity started could listen for the rest of the command which would be passed to openhab as a voice command.  

Commandr (https://play.google.com/store/apps/details?id=com.RSen.Commandr&hl=en) seems to be able to register new commands other than 'start XXX' so there might be a way to make a more friendly tag if someone wants to dig around a bit more.

**Comment by belovictor** [comment]
I propose to move all wearable discussions into #73 , ok?
