### ISSUE TITLE
HABdroid installation error -505

### ISSUE THREAD

**Issue by airm** [openhab/openhab.android#54]
PackageInstallerImpl.handleCommitCallback: Error -505 while installing org.openhab.habdroid:
INSTALL_FAILED_DUPLICATE_PERMISSION: Package  org.openhab.habdroid attempting to redeclare permission com.example.gcm.permission.C2D_MESSAGE already owned by de.fcbayern.android

After deinstalling the FCBayern App, I was able to install HABdroid.

Maybe it would be better not to use com.example as a package name?

**Comment by belovictor** [comment]
This is already fixed in current code and will be in stock app with next release to play store.
