### ISSUE TITLE
Multi-Line item text? \n?

### ISSUE THREAD

**Issue by michel53** [openhab/openhab.android#540]
Since updating to the new Android app V 2.0 from 17.12.2017, I have a problem with multi-line items.
Before, I could use something like

Switch    Wall_Plug               "Schaltbare Steckdose1 \n(Wohnzimmer) [%s]"
Number    Shutter1_Power          "Rollo Küchentür \nLeistung [%.1f W]"

and it showed in 2 lines in the Android App (but 1 line in Basic and Classic UI).
Now this is always 1 line, eventually cutting it and showing “…”, making items hard to differentiate.

How can I name items so that the whole text is shown, eventually in 2 lines?
Is/was the "\n" syntax valid or did it work only by accident?
Is there an automatic cutoff or linebreak mechanism?

**Comment by ThomDietrich** [comment]
This is not a supported feature of sitemaps and should hence not be supported by the android app.

I'm not particularly shooting down your idea or saying it's a bad thing. If a function like this is desired, it has to be discussed on a ESH sitemap scope first.

**Comment by mueller-ma** [comment]
Like @ThomDietrich this isnt a supported feature. The text is cut, so it does not overlap with the value/switch/slider etc. 
If you want to have some kind of multiline you can create a text item and show it without a value before the switch.
```
Text item=foo label="Schaltbare Steckdose"
Switch item=Wall_Plug label="(Wohnzimmer) [%s]"
```

**Comment by ThomDietrich** [comment]
@mueller-ma 

I believe it has to read

```java
Text item=foo label="Schaltbare Steckdose []"
```

**Comment by michel53** [comment]
Okay, now I know this was not a supported feature.
I agree with @ThomDietrich that such a feature should be discussed on an ESH sitemap scope so that multiline works on all UIs.
The proposed workaround is okay for me for the moment.

**Comment by mueller-ma** [comment]
Do you want to open an issue in eclipse/smarthome?

**Comment by michel53** [comment]
I hope this is the right location:
[https://github.com/eclipse/smarthome/issues/4789](url)

**Comment by mueller-ma** [comment]
When you post a link to github, just paste the link without any brackets. The link you posted directs to the user "link".

**Comment by michel53** [comment]
Thanks for the hint, corrected.
