### ISSUE TITLE
No text in menu using a phone with RTL language (hebrew)

### ISSUE THREAD

**Issue by gargamelonly** [openhab/openhab.android#544]
The menu of the app has no text. 
Only menu icons are visible.
![screenshot_20171220-110509](https://user-images.githubusercontent.com/29747434/34199239-c9396184-e575-11e7-9042-577c2dd991a7.png)

**Comment by mueller-ma** [comment]
Duplicate of #533

**Comment by gargamelonly** [comment]
How can I help add translations?
Meanwhile, if no translation is available, why not display the default English text?
