### ISSUE TITLE
crash on voiceCommand from widget

### ISSUE THREAD

**Issue by zosky** [openhab/openhab.android#548]
after a few years using OH, i finally decided to make a voiceControl item & some rules. the WAF on this one is high !! thank you for such a cool feature.

on my wife's phone it works flawlessly. on mine, when activated from the widget it crashes every time (after sending the command to OH). it does not crash when voice is launched from inside the app.

i turned on debug & grabbed [logs](https://www.dropbox.com/s/stvtmw3o7e0fjov/habDroid.debug-crash-log-171220.txt?dl=0)... but im not sure what it's telling me. help plz.

**Comment by mueller-ma** [comment]
Can you post the logs here on github?

**Comment by zosky** [comment]
sure, however you like it 
[habDroid.debug-crash-log-171220.txt](https://github.com/openhab/openhab.android/files/1578287/habDroid.debug-crash-log-171220.txt)

**Comment by mueller-ma** [comment]
```
12-20 18:14:58.289 10238 11539 E AndroidRuntime: FATAL EXCEPTION: IntentService[OpenHABVoiceService]
12-20 18:14:58.289 10238 11539 E AndroidRuntime: Process: org.openhab.habdroid, PID: 10238
12-20 18:14:58.289 10238 11539 E AndroidRuntime: java.lang.IllegalArgumentException: Message type not implemented
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at org.openhab.habdroid.core.OpenHABVoiceService.showMessageToUser(OpenHABVoiceService.java:140)
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at org.openhab.habdroid.core.OpenHABTracker.openHABMessage(OpenHABTracker.java:227)
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at org.openhab.habdroid.core.OpenHABTracker.start(OpenHABTracker.java:114)
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at org.openhab.habdroid.core.OpenHABVoiceService.onHandleIntent(OpenHABVoiceService.java:87)
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at org.openhab.habdroid.util.ContinuingIntentService$ServiceHandler.handleMessage(ContinuingIntentService.java:41)
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-20 18:14:58.289 10238 11539 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

https://github.com/openhab/openhab.android/blob/master/mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java#L140

Whats the best way to fix this issue? Show a toast as default?

**Comment by maniac103** [comment]
Personally I'd drop this message completely and only fall back to toasts for error messages.

**Comment by NDR008** [comment]
I have same issue on my s8.
Launching from widget works but it gives me the message that Openhab has stopped.

Launching from within the home is fine.

**Comment by mueller-ma** [comment]
Do you see any notification popping up, when launching from the main view?

**Comment by NDR008** [comment]
Just the voice recognition widget, then confirmation of what message was
understood.

**Comment by NDR008** [comment]
I also just gave it a try on my tablet still running lollipop. Same way of
crashing from the widget.

**Comment by zosky** [comment]
i get a toast with _recognised command: what i say_ ... then the crash
![780086445055543032](https://user-images.githubusercontent.com/112049/34453379-abef8618-ed21-11e7-938f-b9a18a59141f.jpg)

**Comment by NDR008** [comment]
Exactly same
