### ISSUE TITLE
Atmosphere sessions running systems out of memory

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab.android#56]
hey @belovictor !  can you take a look at the this comment https://github.com/openhab/openhab/issues/1961#issuecomment-73418700 ?  Basically on system where items are changing every second we are running out of memory on the server due to too many atmosphere sessions.  I see there was a change to alternate long polling requests, is there another solution?  I'm just trying to patch this together until OH 2 comes out and we can switch out atmosphere for something else.  Thanks!

**Comment by digitaldan** [comment]
@belovictor have you had a chance to look at this yet?  I was hoping to try and fix this over the weekend. Thanks!

**Comment by belovictor** [comment]
This change makes a non-long-polling request after every long-polling request is finished. This was the only way I managed to make it work at all. Without that I never got updates from openHAB for changing items basically. I can change this back to normal, but will it work on the openHAB side?

**Comment by digitaldan** [comment]
It works for me ok, as a reference I use the demo setup with some additional rules that turn everything on and off every second.  Let me get a clean environment setup and do some more testing to really make sure.  Is the app in the store up to date with master?

**Comment by belovictor** [comment]
This is fixed in the linked pull request.
