### ISSUE TITLE
[question] install app on wear

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab.android#57]
Hello!

I've tried installing the Wear App via Android Wear APK Tools, however, I am unable to get it working. The Tool correctly lists all my apps but no matter which wear*.apk I use, nothing seems to be visible on my watch.

Am I doing anything wrong? Which .apk should I install? (using snapshots from Jenkins).

Also, is there any way to include the wear app inside of the normal .apk to get both installed at the same time?

**Comment by belovictor** [comment]
The wear part of the application is empty and was added technically to the project so that anybody who would like to contribute into wearable app will be able to do that without a need to refactor the whole project.

**Comment by petrklus** [comment]
Thanks!

Is there any tutorial similar to the OpenHAB SDK setup?

**Comment by belovictor** [comment]
Well, it is not about openHAB app but more about Android application development I'm afraid. There are quite a lot of tutorials about Android development and wearable.

**Comment by petrklus** [comment]
Yes, that's what I mean - same way OH describes the basic setup of
Eclipse.. is there anything specific for the myOH or is it literally
setting up basic Android toolchain and cloning the repo?

Best,

Petr
