### ISSUE TITLE
OpenHAB2 support

### ISSUE THREAD

**Issue by grzech1983** [openhab/openhab.android#58]
Hello,

Does habdroid supports openhab2? According to cloudbees changelog it should but when I installed latest habdroid (20.01.2015 build) and pointed it to latest openhab2 URL loading icon in habdroid is stuck and nothing from my sitemap is being loaded (I've tried HTTP and HTTPS URLs).

Regards

EDIT: Only thing that is probably working is selecting sitemap. I can select sitemap with name "default" but nothing happens after that.

**Comment by grzech1983** [comment]
Hello,

any chance for response? Even simple "it works on my end" would be enough.

Thanks

**Comment by cdjackson** [comment]
It works on my end :)

**Comment by grzech1983** [comment]
:D. Ok. Thats good information. I've only tested OH2 for a small moment and everything worked fine except HabDroid (I prefer HabDroid over habmin android APP because it is native android app instead of webpage - because this is how it works in habmin android app right?).

**Comment by cdjackson** [comment]
The Habmin app is native android app, although under the hood it is partly a web page but you cant tell the difference. Its quite common these days to write apps in Javascript then compike them as native Android, iOS, Windows... apps.

In any case Habmin isnt ready for prime time yet and habdroid is the best.


Sent from Samsung Mobile

**Comment by grzech1983** [comment]
Yep. I know that a lot of apps use this kind of engine for displaying content and for most of them it is fine but when it comes to home automation/management there is difference (IMHO of course) in performance beween this two apps.

**Comment by cdjackson** [comment]
> Yep. I know that a lot of apps use this kind of engine for displaying content and for most of them it is fine but when it comes to home automation/management there is difference (IMHO of course) in performance beween this two apps.
> 
Possibly - but I don’t see any performance hit in HABmin - most HA software isn’t doing much on the client side. HABmin serves up Sitemaps for example just as fast as HABdroid - the initial app load is slightly slower, but that can probably be improved if I used the release version as it’s considerably smaller. My testbed is a year old Samsung Note-2, so newer machines should be at least as fast.

**Comment by Shibonja** [comment]
I have the same issue, i tried OH2 (distribution-2.0.0-SNAPSHOT-runtime) with demo configuration. Changed the file demo.sitemap to default.sitemap, but with no success, the HabDroid app show's only blank screen. How do you made it work???

**Comment by kaikreuzer** [comment]
I can only get HABDroid working if I configure a local url in the settings - when doing discovery, it also fails to connect for me. I would hope that Victor can help on this.

**Comment by kaikreuzer** [comment]
I should add that only the version on cloudbees (https://openhab.ci.cloudbees.com/job/HABDroid/) is working with openHAB 2, the one in the Play Store is too old. I hope that we will soon have a newer released version as well.

**Comment by Shibonja** [comment]
Thanks, for fast reply :D

**Comment by belovictor** [comment]
@kaikreuzer , are you sure discovery is starting in openhab2? I'm not able to see mdns service announcements on LAN after starting openhab2... At the same time I clearly see the announcement when I start openhab1 and android app discovers it successfully on the same LAN/computer.

**Comment by kaikreuzer** [comment]
> @kaikreuzer , are you sure discovery is starting in openhab2?

Yes. Just tested it again: Downloaded latest runtime from Cloudbees, started it with start.sh and checked with BonjourBrowser on Mac:
![bildschirmfoto 2015-03-23 um 23 21 43](https://cloud.githubusercontent.com/assets/3244965/6791906/0b9e843e-d1b3-11e4-9f23-656d43574d95.png)

**Comment by kaikreuzer** [comment]
You are right - mDNS did not survive the refactoring of the mdns bundle to the io.transport namespace...

**Comment by kaikreuzer** [comment]
Ok, with the latest build of openHAB 2, I can confirm that the discovery works nicely and sitemaps are displayed as expected!
