### ISSUE TITLE
Connection Refused while trying to connecti via remoteURL

### ISSUE THREAD

**Issue by eluder87** [openhab/openhab.android#59]
Hi Guys,

I have been bashing my head against this for 2 nights and i have done some searching on the issue but cant seem to find a fix.
I have left openHAB URL blank and my remoteURL is set to http://127.0.1.1:8080/. I have also tried using http://127.0.1.1:8080/openhab.app?sitemap=demo but it still comes back saying connection refused. I have also checked that my security settings are turned off (security:option=OFF)
Any ideas to what could be causing this?
Thanks.

**Comment by mdeneen** [comment]
127.0.0.1 is localhost, so that's not going to work.  You'll need the ip address of the computer running openHAB.

**Comment by eluder87** [comment]
All fixed thanks for your help, Sorry for the dumb question networking isn't exactly my strong point.
