### ISSUE TITLE
Issue with voice commands (SOLVED)

### ISSUE THREAD

**Issue by eluder87** [openhab/openhab.android#60]
Hi Guys, I am new to Openhab and i am still learning how to do a lot of things. But one thing i cant get my head around is working out how to correctly code the voice command rules. I followed the wiki and i have wrote it like so.
ITEM:
String VoiceCommand
Switch office  (FF_Office, Lights)  {hue="1"}

RULE:

rule VoiceControl
 when
  	Item VoiceCommand received command  
 then
 Light_FF_Office_Ceiling.sendCommand(OFF)
 end

Now this rule works fine if i tell it OFF it turns my office light OFF but i also noticed that if i say any random word it will also turn it OFF. So i was wondering if someone can show me or provide me an example of how to code the rule properly so i can say "Turn Office Light OFF" and have it switch OFF.
Thanks

**Comment by dominicdesu** [comment]
Hi,
you are heading into the right direction. What you need now is a check in your rule for the actual voice command received:
```
var String command = VoiceCommand.state.toString.toLowerCase
if (command.contains("light off") || command.contains("lamp off") {
   // Switch your light off here, e.g. Light_FF_Office_Ceiling.sendCommand(OFF)
}
```

**Comment by eluder87** [comment]
Cheers for that. Did exactly that you showed me but i am now getting a error " missing  ) at { " At the end of this line. if (command.contains("light off") || command.contains("lamp off") {

**Comment by dominicdesu** [comment]
Sorry, missed a bracket. Must of course be
```
if (command.contains("light off") || command.contains("lamp off")) {
```

**Comment by eluder87** [comment]
awesome! works like a charm thanks for the help. :)

**Comment by cribskip** [comment]
Please also take a look at the openhab wiki: there is a sample rule for this task. Please also close the issue if it's done, thanks 😊
