### ISSUE TITLE
Webview and php site with form posting

### ISSUE THREAD

**Issue by rush131** [openhab/openhab.android#68]
Hello,

I'm trying to load an php website into the webview in order to input a pin to arm and disarm the alarm. The php page uses forms and on code input, it submits the form to itself. When submitting the form, the webview gives me this error: "HTTP error 404, problem accessing /keypad.php. Reason: ProxyServlet: keypad.php. powered by Jetty://". This works OK when I open the webview in a browser, directly from openhab, but it does not work in android app. Here is the webview code:

        Frame label="Alarm"{
                Group item=Alarm label="Alarm" icon="lock" {
                        Webview label="keypad" url="http://localhost/keypad.php" height=12
                        Text item=AlarmStatus label="Status" icon="lock"
                }
        }

And here is the php code:
http://pastebin.com/xmsgnMgr

Both the webserver and openhab server are on the same machine.

**Comment by rush131** [comment]
Found another issue with the webview: when creating an Weather Binding, and setting up custom layout as described here (https://github.com/openhab/openhab/wiki/Weather-Binding), the layout is visible on the openhab ui when using a browser, but the android app just displays a blank page..

**Comment by digitaldan** [comment]
As of 1.5 or 1.6 webview requests go through a proxy servlet for security
reasons, this unfortunately breaks loading websites.  There is a thread
about this somewhere, but I can't seem to find it right now.

**Comment by rush131** [comment]
Thank you Dan!
Any chance of fixing this, or is it going to stay broken? :)

**Comment by digitaldan** [comment]
Not my call,  there was a discussion about the proxy servlet here
https://github.com/openhab/openhab/pull/57 ,  I actualy have the proxy
disbaled on webviews for my setup so I would be happy to fix it if kai is
ok with it.  If someone wants to open a bug I would be happy to comment on
it.

**Comment by belovictor** [comment]
This is not an Android app problem, rather it is a case about proxy in openHAB itself.
