### ISSUE TITLE
dark theme is missing

### ISSUE THREAD

**Issue by Human** [openhab/openhab.android#87]
Commit 4ba5c6dc1fb7c693b76c52c602520a45808bbf6f removed the dark theme and the ability to choose it.

**Comment by belovictor** [comment]
This was done by intension cause I think that our app looks ugly in dark material design. Do you think it looks fine?

**Comment by Human** [comment]
I personally use it at night and for a dedicated home theater control device (old phone, mounted on the wall). I think having the choice is better than not having it.

**Comment by belovictor** [comment]
Well, I'm not against it. Can you post screenshots of how Dark Material looks like?

**Comment by Human** [comment]
![screenshot_2015-04-05-08-56-05](https://cloud.githubusercontent.com/assets/40866/6997039/d899691c-db78-11e4-92f5-4db9bff6a44d.png)

![screenshot_2015-04-05-08-56-11](https://cloud.githubusercontent.com/assets/40866/6997040/e14149fe-db78-11e4-9141-d51273e3d74a.png)

**Comment by belovictor** [comment]
Sorry for bothering, but can you post a screenshot of first page in demo mode?

**Comment by Human** [comment]
![screenshot_2015-04-05-12-27-40](https://cloud.githubusercontent.com/assets/40866/6997600/3d471fd8-db8f-11e4-9b62-6015dc8ba152.png)

**Comment by cribskip** [comment]
Separators should be colored differently IMHO

**Comment by kaikreuzer** [comment]
Yeah, possibly black separators might be nice. I'd also vote to change the orange theme to something less flashy - possibly some grey shades might be a good fit, if this is possible.
In general, I agree that a black theme is a valuable option to have.

**Comment by belovictor** [comment]
Do you mean changing orange for dark theme or for both of them?

**Comment by kaikreuzer** [comment]
Only for dark theme.

**Comment by teichsta** [comment]
> Yeah, possibly black separators might be nice. I'd also vote to change the orange theme to something less flashy

**Comment by robnielsen** [comment]
You can find material color palette at http://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by belovictor** [comment]
As pull request is merged we can now take dev snapshot and discuss the colors.

**Comment by kaikreuzer** [comment]
> You can find material color palettes at http://www.google.com/design/spec/style/color.html#color-color-palette

I'd go for grey for the dark theme.

**Comment by belovictor** [comment]
I'm afraid that grey will break visual identity cause orange is a natural color of openHAB :-(

**Comment by kaikreuzer** [comment]
Well, just consider the dark theme as a b&w version - then the orange is just a shade of grey :-)

**Comment by curlyel** [comment]
I do agree with Kai. Some less flashy color make the ui look more sophisticated/professional. I would vote for gray-shaded colors too combined with very few colorful accents.

**Comment by belovictor** [comment]
Ok, then my proposal would be to name them "Display mode" instead of "Theme" and then name them "Day" and "Night" instead of "Light" and "Dark". This will make less user confusion then. Any cons?

**Comment by kaikreuzer** [comment]
I don't think that it will mean less confusion. "Dark theme" is a well-known concept and I think everybody knows what to expect from it. Under "Display mode", I would rather expect things like orientation, brightness, screensaver settings, etc.

**Comment by cribskip** [comment]
+1 for Kai. I also see "display mode" different from theme. 

The dark theme might just be shades of grey, with the icons being the only color on the screen (besides label and /or value colors)

**Comment by belovictor** [comment]
I've changed the colors so have a look at current snapshot?

**Comment by cribskip** [comment]
Current "dark/gray" looks really good and professional :+1:

**Comment by robnielsen** [comment]
I guess I'd like some more color, maybe a darker  orange on the top. #BF360C  for example.

**Comment by cribskip** [comment]
Nice addition @robnielson! How about dark, light and a "dim" theme?

**Comment by belovictor** [comment]
@robnielsen , do you mean the color of status bar, or the color of action bar?

**Comment by kaikreuzer** [comment]
I actually like the dark theme as it is - I am using it for the past weeks already :-)

**Comment by robnielsen** [comment]
The bar that has openHAB on it.

**Comment by belovictor** [comment]
I would leave it as it is for now, as suggested by @kaikreuzer
