### ISSUE TITLE
habdroid crashes when notifications used too early

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab.android#98]
Hi,

after commit 9c0b215cbc3369521c4cdae258c6af266b1b501c, habdroid is able to display previous notifications using "Notification" from the drawer.
However, this item is always visible - even when openhab has not been discovered. When a user selects this function in this time slot, habdroid crashes.

Proposed solution: Hide the function until discovery/tracker has finished.

Cheers
Sascha

**Comment by belovictor** [comment]
This function shows up if my.openHAB is configured for remote URL and username/password are configured and should not be anyhow connected with discovery of openhab. I'll check this.
